package done;

import org.junit.Test;

import java.util.Objects;
import java.util.Scanner;
import java.util.Set;
import java.util.function.Supplier;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static java.util.Collections.emptySet;

@SuppressWarnings("unused")
public class CustomCustoms {

    public static void main(String[] args) {
        try (Scanner in = new Scanner(INPUT)) {
            int sum = Stream.generate(new BatchSupplier(in))
                    .takeWhile(Objects::nonNull)
                    .mapToInt(CustomCustoms::countQuestionsAllInGroupTrue)
                    .sum();

            System.out.println("Result: " + sum);
        }
    }

    private static int countQuestions(String line) {
        return (int) line.chars()
                .filter(c -> !Character.isWhitespace(c))
                .distinct()
                .count();
    }

    private static int countQuestionsAllInGroupTrue(String line) {
        String[] group = line.trim().split("[\\s]");
        return Stream.of(group)
                .map(CustomCustoms::toSet)
                .reduce(CustomCustoms::disjoint)
                .orElse(emptySet())
                .size();
    }

    private static <T> Set<T> disjoint(Set<T> g1, Set<T> g2) {
        g1.retainAll(g2);
        return g1;
    }

    private static Set<Integer> toSet(String group) {
        return group.chars().boxed().collect(Collectors.toSet());
    }

    private static final String INPUT = "" +
            "abc\n" +
            "\n" +
            "a\n" +
            "b\n" +
            "c\n" +
            "\n" +
            "ab\n" +
            "ac\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "b\n";

    private static final String INPUT2= "" +
            "atxmhdzkjgivwcqu\n" +
            "conirfdgplhvsa\n" +
            "ghbvdefsaniyc\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "cas\n" +
            "xc\n" +
            "cz\n" +
            "\n" +
            "sdxtfzo\n" +
            "stfzno\n" +
            "\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "nkjexbhrswugov\n" +
            "jxugwhbroves\n" +
            "\n" +
            "meqnof\n" +
            "vxwhzpmqo\n" +
            "jno\n" +
            "bkoliycr\n" +
            "\n" +
            "u\n" +
            "u\n" +
            "\n" +
            "rbyuds\n" +
            "surjb\n" +
            "lbrxsawhu\n" +
            "\n" +
            "sd\n" +
            "dq\n" +
            "ds\n" +
            "ds\n" +
            "\n" +
            "zo\n" +
            "z\n" +
            "vz\n" +
            "\n" +
            "czhuijskmt\n" +
            "utszkmhijc\n" +
            "kzmuictsjh\n" +
            "chimtzksuj\n" +
            "\n" +
            "uwhmbl\n" +
            "wblur\n" +
            "wublm\n" +
            "bflesuw\n" +
            "\n" +
            "bo\n" +
            "wcszvk\n" +
            "\n" +
            "htfsqoriyngzjbvx\n" +
            "dujtmikcpzrwehaxl\n" +
            "\n" +
            "rubwcon\n" +
            "vwo\n" +
            "omwhl\n" +
            "rxwbo\n" +
            "\n" +
            "aj\n" +
            "aj\n" +
            "faj\n" +
            "aj\n" +
            "\n" +
            "nwfmajzslokrxhgtyq\n" +
            "vicapdwkbuh\n" +
            "\n" +
            "vdwysctjq\n" +
            "jmilqgh\n" +
            "jqgf\n" +
            "\n" +
            "tnoemqphdcbj\n" +
            "jfavhsqkntg\n" +
            "\n" +
            "qjrpfwckgbvenam\n" +
            "qpucwvgmjfabro\n" +
            "\n" +
            "fmqwzhbytnacdr\n" +
            "fmncdrhqywatzb\n" +
            "\n" +
            "r\n" +
            "w\n" +
            "w\n" +
            "\n" +
            "umrbzaypkwinh\n" +
            "eyuwhi\n" +
            "yhuwie\n" +
            "ehiywu\n" +
            "hwyui\n" +
            "\n" +
            "dxynjlhfbi\n" +
            "fjxd\n" +
            "mxdfj\n" +
            "fdxmj\n" +
            "jdfoxs\n" +
            "\n" +
            "ikdeutpqynboghfs\n" +
            "yjfkmidnqtgueb\n" +
            "\n" +
            "jpzfsbwgdkvtiymneuca\n" +
            "vbpkjgtdaucezymwsn\n" +
            "ctmydbsjgapewnzuvk\n" +
            "\n" +
            "gyxjvqk\n" +
            "gwkjfvi\n" +
            "rkcbegvjm\n" +
            "\n" +
            "sgzakoq\n" +
            "koszqa\n" +
            "\n" +
            "qmzjhtsodfurnpegy\n" +
            "aurfdgojzmetpnbis\n" +
            "gtezmrodujfpsyn\n" +
            "\n" +
            "qyknpixtrfuolw\n" +
            "fkpwgntyxlqumrio\n" +
            "yrflupnoqitxwak\n" +
            "iypferukwqtonlx\n" +
            "qurtxlnoiwkyfp\n" +
            "\n" +
            "xbweyquhnairjtzopvmg\n" +
            "byhuwnaxqoimtzepvjrg\n" +
            "jzxbqmrnwgvdpaeyotuhi\n" +
            "nwtpovmruhqieyjxabgz\n" +
            "yoeamwhqbrtjvgniupzx\n" +
            "\n" +
            "ic\n" +
            "ic\n" +
            "ic\n" +
            "iuperc\n" +
            "acsi\n" +
            "\n" +
            "oicl\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "uyxbejfrqhvpcknziowtlad\n" +
            "fxhnwdebmjzpitkgqualrv\n" +
            "\n" +
            "me\n" +
            "me\n" +
            "wme\n" +
            "yemc\n" +
            "em\n" +
            "\n" +
            "zxgncvbdrewkyls\n" +
            "lzbnwesxckgryvd\n" +
            "krvsyadlgbzecxwn\n" +
            "nwcblgzdsxrkevy\n" +
            "vgwbrxleckzydns\n" +
            "\n" +
            "bdrhenpgofqyv\n" +
            "uazwsjlitk\n" +
            "wlcatxm\n" +
            "\n" +
            "jsdnlwkto\n" +
            "onkdhysjtwl\n" +
            "ojhkstnlfwd\n" +
            "wfjeodnklts\n" +
            "wkngdtqulaozjs\n" +
            "\n" +
            "jseag\n" +
            "lazegosfj\n" +
            "gaesj\n" +
            "rjagse\n" +
            "\n" +
            "vycnwzfah\n" +
            "yhwanzcvf\n" +
            "fycvwzhna\n" +
            "\n" +
            "kdenoqr\n" +
            "drnokqe\n" +
            "\n" +
            "fudosahtj\n" +
            "hzygvbjdu\n" +
            "qubhjdep\n" +
            "ezdujxbhw\n" +
            "\n" +
            "asrfbcnuywm\n" +
            "nyrawufmbcs\n" +
            "mbyrasnufwc\n" +
            "fusrncywmba\n" +
            "racbyufmnsw\n" +
            "\n" +
            "eldyp\n" +
            "pgdjb\n" +
            "jdpb\n" +
            "\n" +
            "xiky\n" +
            "ximqy\n" +
            "yxinl\n" +
            "iyx\n" +
            "yiekx\n" +
            "\n" +
            "lzbmt\n" +
            "otbpu\n" +
            "\n" +
            "upobyhamecgwtjkx\n" +
            "kytepobcxhwuajgm\n" +
            "kobtcgphxeujmwya\n" +
            "tbpjehaukgycwomx\n" +
            "\n" +
            "lgjrbcymkatpx\n" +
            "pbazritkysjmlx\n" +
            "tkpymrejqxab\n" +
            "tayxbjnlourdfpkwm\n" +
            "\n" +
            "kvqxyecmirno\n" +
            "einsmcdxkyrvoq\n" +
            "evxqrkoiymnc\n" +
            "yvikqxecmron\n" +
            "yqemnrickvox\n" +
            "\n" +
            "tlroieuszcwpkdbmh\n" +
            "ypgxfdatn\n" +
            "jqpdvt\n" +
            "\n" +
            "kuynfegcxrt\n" +
            "ytnuzecgfxk\n" +
            "xhgsflynecw\n" +
            "\n" +
            "q\n" +
            "q\n" +
            "\n" +
            "mu\n" +
            "um\n" +
            "uwm\n" +
            "mu\n" +
            "um\n" +
            "\n" +
            "abyhrzfe\n" +
            "yqhrfebz\n" +
            "frhzeyb\n" +
            "bkfreyazh\n" +
            "ebrzyhf\n" +
            "\n" +
            "vdo\n" +
            "se\n" +
            "x\n" +
            "x\n" +
            "\n" +
            "peckiwfxzqsal\n" +
            "paiuofxlqyczeswk\n" +
            "zxlarkseiwfcpnj\n" +
            "lnkijaeswqpfzcx\n" +
            "mtpilgsbchfwzexka\n" +
            "\n" +
            "vnuoec\n" +
            "fveonub\n" +
            "evsrniquo\n" +
            "ondeuav\n" +
            "nuovte\n" +
            "\n" +
            "ypnmo\n" +
            "omypn\n" +
            "ympon\n" +
            "\n" +
            "pgbej\n" +
            "pjbg\n" +
            "pjgb\n" +
            "jpbg\n" +
            "\n" +
            "xwognfphakcjritb\n" +
            "fvcoexrpughatk\n" +
            "orahqctxfzgkp\n" +
            "xgfrhcokmapt\n" +
            "\n" +
            "g\n" +
            "ytab\n" +
            "\n" +
            "q\n" +
            "yw\n" +
            "\n" +
            "ravlebmfjodkzgu\n" +
            "rujyetlnszmkvad\n" +
            "\n" +
            "mgktpszhdeolvbqa\n" +
            "oqnbagktzpvshdle\n" +
            "sltvkgpezabqdh\n" +
            "kpsghlqzedbaft\n" +
            "dknetrlqgpzahbs\n" +
            "\n" +
            "rejugfqtbaklixcmhodwsnyzv\n" +
            "gmukinscxjpvehbrodfqyawz\n" +
            "aswfqonbuvhkdizjgmrxyec\n" +
            "jrgiyhdmwcexuqfzoabkvsn\n" +
            "\n" +
            "nfcsiavmzglehorwd\n" +
            "orcmwveigashnzdfl\n" +
            "gcmhdvfawlsnzxrioe\n" +
            "qfehovruzlgncwmsida\n" +
            "\n" +
            "qrufx\n" +
            "frozu\n" +
            "qfsrjub\n" +
            "nvfuxr\n" +
            "wcydflreu\n" +
            "\n" +
            "tawnehfqjsc\n" +
            "ocaznquitbs\n" +
            "pnaqcshtv\n" +
            "\n" +
            "twvz\n" +
            "tzwv\n" +
            "zvwt\n" +
            "\n" +
            "ejv\n" +
            "vje\n" +
            "ejv\n" +
            "\n" +
            "zicejtfhnuq\n" +
            "hzjcquitenf\n" +
            "vjznuqhtiefc\n" +
            "tuqcnjefzih\n" +
            "hitnjezfcuq\n" +
            "\n" +
            "w\n" +
            "w\n" +
            "f\n" +
            "\n" +
            "jufqelnptbragsmocdwk\n" +
            "embpluswrkdovjnqcfg\n" +
            "\n" +
            "spzytuih\n" +
            "tevqnxrhi\n" +
            "\n" +
            "nxeolsqucv\n" +
            "losqenvu\n" +
            "nveljqugso\n" +
            "opurwesnvql\n" +
            "vbeflqugwnosrp\n" +
            "\n" +
            "fcekwrx\n" +
            "vczrowmxa\n" +
            "\n" +
            "ydtqbl\n" +
            "ldytbq\n" +
            "bdqltyv\n" +
            "qytldb\n" +
            "\n" +
            "fzbucokxnimrdvsplta\n" +
            "ztnkgarvdlxfiwu\n" +
            "udzxtkfvhrnlia\n" +
            "\n" +
            "qnzmokyluv\n" +
            "oczmvlnyqku\n" +
            "kvlqzymuon\n" +
            "\n" +
            "qchbuvepxwm\n" +
            "ubxvpcwd\n" +
            "wsubcnvprdatx\n" +
            "rvpbxydcwu\n" +
            "\n" +
            "ibeayjghko\n" +
            "cslrtwdvmbxqpfnuoz\n" +
            "\n" +
            "uzp\n" +
            "uzp\n" +
            "pzu\n" +
            "puz\n" +
            "zup\n" +
            "\n" +
            "gqhbwupsmeklf\n" +
            "ebmlkfgshpwuq\n" +
            "mbsqkpgewulhf\n" +
            "ufphbmsqlkgwe\n" +
            "\n" +
            "pxsqkfa\n" +
            "pkmcrqefgx\n" +
            "kfxpq\n" +
            "pqkyfx\n" +
            "kzdqfxp\n" +
            "\n" +
            "yimkxaqtcnospueg\n" +
            "pngtsyqkcuoamiex\n" +
            "ncygqsmatiupxkeo\n" +
            "quichtngeypsaxkom\n" +
            "\n" +
            "jew\n" +
            "eylr\n" +
            "\n" +
            "uc\n" +
            "uc\n" +
            "cu\n" +
            "\n" +
            "gapelusnokrw\n" +
            "zloakewgpsrun\n" +
            "pnrkwosagule\n" +
            "nuwaesypkgomlrv\n" +
            "iarpwkugolhesn\n" +
            "\n" +
            "qdyzmoitxflwbnver\n" +
            "udwlojxfipkshacnqvg\n" +
            "\n" +
            "butecshxlvanoy\n" +
            "octsbudkilhnzeyavrxg\n" +
            "tyavloucspenbxh\n" +
            "qebhpxsunovalmwjcty\n" +
            "xhvstmbaulyceon\n" +
            "\n" +
            "vtspwicxbz\n" +
            "spbzixvtcew\n" +
            "vcxpwtsibz\n" +
            "cizvpxstwb\n" +
            "tiwcbxpszv\n" +
            "\n" +
            "avrgucfhxjblspwzmdtnyiqek\n" +
            "wvlmbfipargeyxscjthznuk\n" +
            "\n" +
            "clzbqry\n" +
            "lrebz\n" +
            "zlbpr\n" +
            "urlzb\n" +
            "lbzr\n" +
            "\n" +
            "dvqtxlgowke\n" +
            "idtvexwlog\n" +
            "wvlotxgde\n" +
            "dygtopxlvwe\n" +
            "\n" +
            "xuybmdgwacejltzkhr\n" +
            "lojbxtwyrhdgufkpec\n" +
            "lyebujkxhtrcwpdg\n" +
            "\n" +
            "zhxigcsotywpuelband\n" +
            "girdhbonymwfpuvx\n" +
            "\n" +
            "profkjw\n" +
            "nylxubzptsg\n" +
            "vidrop\n" +
            "ewpfh\n" +
            "\n" +
            "vc\n" +
            "cuv\n" +
            "vc\n" +
            "\n" +
            "gjytrlzpeonxwcdbafh\n" +
            "dhxgwpyjlroazenftcb\n" +
            "\n" +
            "fymaqc\n" +
            "afmcqy\n" +
            "\n" +
            "wxcazpmrfyb\n" +
            "pnvrzhacfji\n" +
            "zvctfapr\n" +
            "tpzlchiafr\n" +
            "\n" +
            "izrdmuwebqk\n" +
            "mreahwzsuqd\n" +
            "ruqyezahwpdnm\n" +
            "\n" +
            "rj\n" +
            "jr\n" +
            "rj\n" +
            "fjr\n" +
            "rj\n" +
            "\n" +
            "txjnrfocwlemuiapbh\n" +
            "lqjuaweo\n" +
            "aujlkesoyw\n" +
            "jwoealu\n" +
            "ujodaelwvkgz\n" +
            "\n" +
            "zo\n" +
            "zo\n" +
            "z\n" +
            "mzd\n" +
            "\n" +
            "dx\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "mprvcwluqo\n" +
            "tloukican\n" +
            "\n" +
            "odvtfhqjawgpzbxre\n" +
            "tgoxqwrfhjcbaev\n" +
            "\n" +
            "fdaljwguepsiykxz\n" +
            "lpseagdjzufkywix\n" +
            "sywukzgjlfixaped\n" +
            "bpuyjswgrkdaxliezf\n" +
            "\n" +
            "uncv\n" +
            "icnv\n" +
            "cnvu\n" +
            "\n" +
            "ktaqgr\n" +
            "twgaqykrjm\n" +
            "vqgpkfuxtchrae\n" +
            "\n" +
            "armwntdgzfxikehupj\n" +
            "xtfhgjmrdzpaiunewk\n" +
            "\n" +
            "yxrkv\n" +
            "vfykru\n" +
            "rviesjyt\n" +
            "\n" +
            "plyfkjxasvuzdcgbtwi\n" +
            "xzjiwylkpctbfvdugsa\n" +
            "fkxjvlbactydpgzsuiw\n" +
            "qgwcbfjtypzkvluxsdiam\n" +
            "btzplfwigkdjasxyvuc\n" +
            "\n" +
            "gwloycsuz\n" +
            "musyrzwlaoge\n" +
            "uovyzhlswgc\n" +
            "\n" +
            "qndaivetjcgblwzsykhu\n" +
            "agorkdnxvmswpfhqiuetzyc\n" +
            "\n" +
            "fgxopdsinm\n" +
            "msgdeponfxhi\n" +
            "xpodgmsinf\n" +
            "nfmodxisgp\n" +
            "\n" +
            "rx\n" +
            "x\n" +
            "x\n" +
            "oxed\n" +
            "x\n" +
            "\n" +
            "twrjcfumd\n" +
            "cvjbfuw\n" +
            "oyasjulepkgwx\n" +
            "umirnjw\n" +
            "\n" +
            "unhbzo\n" +
            "hnuobz\n" +
            "uzonhb\n" +
            "ubhyonz\n" +
            "uzhbon\n" +
            "\n" +
            "arfjnt\n" +
            "netj\n" +
            "etnqj\n" +
            "yjxsntm\n" +
            "fntjvg\n" +
            "\n" +
            "khqap\n" +
            "aqhp\n" +
            "pjovizqh\n" +
            "qph\n" +
            "\n" +
            "uosyjc\n" +
            "zrledfqmpi\n" +
            "kjxotw\n" +
            "tgay\n" +
            "\n" +
            "nrzckijesf\n" +
            "ihrbgsjn\n" +
            "jshbintrom\n" +
            "hrmnsibj\n" +
            "mjsirwn\n" +
            "\n" +
            "ilqbcavozr\n" +
            "tarjqpolv\n" +
            "\n" +
            "piokgqecjz\n" +
            "gfjkleochzip\n" +
            "peczjiokg\n" +
            "zkpjioegc\n" +
            "zciekojgp\n" +
            "\n" +
            "pwi\n" +
            "wip\n" +
            "pi\n" +
            "pi\n" +
            "pih\n" +
            "\n" +
            "gmjlzhpkqbfiuvdsy\n" +
            "djfvsyglzcikmqbup\n" +
            "mzsjgidkewauvqflypb\n" +
            "vzuglyndmftspikqjb\n" +
            "\n" +
            "l\n" +
            "jl\n" +
            "\n" +
            "yiucsmkgalz\n" +
            "iaulzghkmnc\n" +
            "\n" +
            "pny\n" +
            "pkyn\n" +
            "\n" +
            "mgflvdoj\n" +
            "vlmodfgj\n" +
            "joglvmidf\n" +
            "jdomlvgf\n" +
            "\n" +
            "bctiyxqnazrpd\n" +
            "qautyfzjegx\n" +
            "tyqaxzojv\n" +
            "qajgytzfx\n" +
            "xqazylt\n" +
            "\n" +
            "wmkauglpbyzno\n" +
            "djrhciqfxs\n" +
            "\n" +
            "zvk\n" +
            "zkv\n" +
            "\n" +
            "vrlencohidajmxub\n" +
            "xordabecpnluvmhi\n" +
            "njrieodvaclbhumx\n" +
            "uebfcsiorldaynvxmh\n" +
            "\n" +
            "m\n" +
            "m\n" +
            "om\n" +
            "m\n" +
            "\n" +
            "elyhutb\n" +
            "ethub\n" +
            "utebh\n" +
            "txzuehdgbnr\n" +
            "ubeth\n" +
            "\n" +
            "os\n" +
            "o\n" +
            "\n" +
            "va\n" +
            "hv\n" +
            "hv\n" +
            "\n" +
            "espkqfnj\n" +
            "neqp\n" +
            "nepq\n" +
            "enqp\n" +
            "nqpre\n" +
            "\n" +
            "mzthqn\n" +
            "drnmtzq\n" +
            "tqmnxyizw\n" +
            "\n" +
            "kvt\n" +
            "ftv\n" +
            "vlt\n" +
            "\n" +
            "vasmgbthenrwxdicl\n" +
            "xcbstgrnvedwauimhl\n" +
            "eamctuvdgsrhxniblw\n" +
            "bknedmhcxigrwtlvsa\n" +
            "\n" +
            "yomwcsxjienprztgubklvd\n" +
            "ivfgqukempnbwaryj\n" +
            "\n" +
            "huvpmdyswlj\n" +
            "wpyhvljmsud\n" +
            "mdhwjvuspyl\n" +
            "wlypuvmjdhs\n" +
            "lmjwhyvspud\n" +
            "\n" +
            "lmwjpzcoavteiq\n" +
            "mlwkogxvabrqejci\n" +
            "ajmhcedvliqwo\n" +
            "vomafiwqljcue\n" +
            "\n" +
            "mpukzsthlv\n" +
            "vwzpkmhult\n" +
            "kuvhwtzmlp\n" +
            "vhmjztplku\n" +
            "utmvczpkhl\n" +
            "\n" +
            "ghmjkozbcevyrdixwputf\n" +
            "ejmyvnpgzkwbuxfoctdr\n" +
            "gdjmetkfxourplyvwcbz\n" +
            "rojxycmfteuvwbkpgzd\n" +
            "eywujmctvqgfdzkxrobp\n" +
            "\n" +
            "thoagp\n" +
            "btaphg\n" +
            "ptaghwm\n" +
            "\n" +
            "vnmuxtqjifowya\n" +
            "etqlonrwmfadzpxbuj\n" +
            "gxjquatnmowvf\n" +
            "onmfctjuqxakw\n" +
            "\n" +
            "beinxhzlmjatkc\n" +
            "hmxctiklajnbz\n" +
            "zlnkxctjhambi\n" +
            "tlxzhknmwjacbui\n" +
            "\n" +
            "ycvpzimohndk\n" +
            "imyzekhpcod\n" +
            "\n" +
            "peaxqrgofmjbytuzvd\n" +
            "wduhliarofgxzntjev\n" +
            "jgasdekoutvrfxbz\n" +
            "\n" +
            "pkstbjaclrzd\n" +
            "kelpszrmg\n" +
            "eojrskczltu\n" +
            "ihrvlzxqfsyk\n" +
            "\n" +
            "rpjdlcybgniahuzqs\n" +
            "zhpgruqjtcsabnidyl\n" +
            "utljniqdrpsbzhaygc\n" +
            "znojdrpcuiyqshablg\n" +
            "\n" +
            "xtnjlk\n" +
            "xknjti\n" +
            "nxkjt\n" +
            "tkjxn\n" +
            "\n" +
            "hcleuvbargstowm\n" +
            "bhwoulsegvtramc\n" +
            "hmasguvceltwobr\n" +
            "arutogvschmeblw\n" +
            "servlmabghckwotu\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "o\n" +
            "oy\n" +
            "o\n" +
            "\n" +
            "gtjbzkvas\n" +
            "bgkjvtzsapl\n" +
            "zrvtgwcakfjbso\n" +
            "tjbkugvasz\n" +
            "vbagszkjt\n" +
            "\n" +
            "gfeoirwlbmdjhk\n" +
            "kirjwlhmoebfp\n" +
            "rolkeiwbhmjf\n" +
            "hbirkejwfmlo\n" +
            "\n" +
            "yzptkfhal\n" +
            "tlzfkyhap\n" +
            "tplzyhfka\n" +
            "hfplztkay\n" +
            "\n" +
            "vmrqh\n" +
            "vhjmxqgyidw\n" +
            "qhmnv\n" +
            "\n" +
            "jdhwkilngubeoa\n" +
            "sxpluz\n" +
            "\n" +
            "jusbk\n" +
            "uxsz\n" +
            "vylqdmugtpne\n" +
            "azfu\n" +
            "\n" +
            "zxtbn\n" +
            "tbnx\n" +
            "tbxn\n" +
            "btwxnu\n" +
            "naxdbt\n" +
            "\n" +
            "v\n" +
            "v\n" +
            "v\n" +
            "v\n" +
            "\n" +
            "ioruk\n" +
            "uriko\n" +
            "\n" +
            "unmxsykzgcilw\n" +
            "nokmu\n" +
            "mjnuqk\n" +
            "akunmv\n" +
            "\n" +
            "rfyibxnevstdz\n" +
            "fsextzdnvbyir\n" +
            "\n" +
            "ehsdnwqugifbvjlk\n" +
            "xkesuhnfldijbytgwv\n" +
            "ivjqhwfdgskenulb\n" +
            "vlwijqbsfkzudegnh\n" +
            "ibudhwelgfkvsqnj\n" +
            "\n" +
            "whxsbrjkqy\n" +
            "dxhkwfsg\n" +
            "hxuonzvictapme\n" +
            "\n" +
            "ui\n" +
            "ui\n" +
            "iu\n" +
            "\n" +
            "ofzuh\n" +
            "czquo\n" +
            "zohu\n" +
            "uzof\n" +
            "\n" +
            "akphewcvmiqzuxdsf\n" +
            "frmsviubcqgkzdwxjnh\n" +
            "\n" +
            "jywpvmdhut\n" +
            "xjeakczsi\n" +
            "\n" +
            "xaenzqsirfm\n" +
            "xzsanmqifer\n" +
            "xzfoqrsajmein\n" +
            "\n" +
            "ypirboxntkl\n" +
            "yobrxintkpl\n" +
            "\n" +
            "benomiyjqdptszaxc\n" +
            "ncayqsmbjfzpotx\n" +
            "\n" +
            "poygwzfkuahrvqimbnscjdexlt\n" +
            "xqwnagemrlscbdouykhivjzftp\n" +
            "\n" +
            "vsphtodb\n" +
            "dstvobp\n" +
            "dvpsrbomt\n" +
            "htovbdsp\n" +
            "psodbtv\n" +
            "\n" +
            "dyxao\n" +
            "oabtscl\n" +
            "vhgnaui\n" +
            "aesm\n" +
            "eak\n" +
            "\n" +
            "gw\n" +
            "krosgqelnc\n" +
            "\n" +
            "hvnfalkbdcexi\n" +
            "beunfqcaxivkdl\n" +
            "linxezbfcakdv\n" +
            "kdxbiecfpavnl\n" +
            "\n" +
            "bp\n" +
            "qul\n" +
            "b\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "wbvefx\n" +
            "huqymact\n" +
            "gpir\n" +
            "moykz\n" +
            "dju\n" +
            "\n" +
            "dt\n" +
            "dt\n" +
            "ted\n" +
            "dt\n" +
            "td\n" +
            "\n" +
            "elhjvm\n" +
            "mu\n" +
            "omnap\n" +
            "fywtsmrc\n" +
            "ogrzm\n" +
            "\n" +
            "efb\n" +
            "bfr\n" +
            "fb\n" +
            "\n" +
            "puszjmhfo\n" +
            "axjwtomegyrku\n" +
            "ldvbujchofmz\n" +
            "jmdoupl\n" +
            "\n" +
            "bvweypzsfroah\n" +
            "knpleztqcgrvdashfujmyio\n" +
            "\n" +
            "rgdtzhj\n" +
            "ohswzxaijd\n" +
            "mlhfduvznj\n" +
            "\n" +
            "faqdszhwtovk\n" +
            "dhfvskonzalurmtqwc\n" +
            "\n" +
            "ectigrqjnhyzvxomlp\n" +
            "gprjuxloceibv\n" +
            "elricvspxjog\n" +
            "fivcorpxjgel\n" +
            "rclogpejxdiv\n" +
            "\n" +
            "cgshrel\n" +
            "anfsk\n" +
            "\n" +
            "y\n" +
            "smgwxh\n" +
            "d\n" +
            "d\n" +
            "t\n" +
            "\n" +
            "xwvtlpayobgshjq\n" +
            "tahyjpxlqogwsc\n" +
            "slgwptojqhxy\n" +
            "tzywskjlqhpxfg\n" +
            "\n" +
            "xakmubfreyop\n" +
            "zsaxruky\n" +
            "kayruxst\n" +
            "axulykqsr\n" +
            "yukrax\n" +
            "\n" +
            "gqhsy\n" +
            "vdkc\n" +
            "ikexpt\n" +
            "alujfmnr\n" +
            "\n" +
            "qd\n" +
            "dq\n" +
            "cdspk\n" +
            "dt\n" +
            "\n" +
            "kv\n" +
            "lvk\n" +
            "\n" +
            "lcn\n" +
            "msnyx\n" +
            "uepnl\n" +
            "\n" +
            "idwqrmpjzo\n" +
            "dojqzmpiw\n" +
            "\n" +
            "yboluqi\n" +
            "xzbenhvwftos\n" +
            "\n" +
            "vsqmcylrugfezitxbhpnaw\n" +
            "ebcxztpvgaswfyiuqolhmn\n" +
            "ywqmpxzesuovtfighclanb\n" +
            "\n" +
            "fwpxel\n" +
            "zlefpxwm\n" +
            "\n" +
            "xahkdvyig\n" +
            "ugdixykhav\n" +
            "hagkivydx\n" +
            "ahykgjvdix\n" +
            "\n" +
            "fqypwlzaxcnh\n" +
            "mbjfrzpakwd\n" +
            "\n" +
            "foajsvbkqnwurhmtic\n" +
            "jfwxuhmlyetcpgra\n" +
            "\n" +
            "saynjgeklirmfozuth\n" +
            "tskreflaogzcmnyiujh\n" +
            "jiylarkmshonuftegz\n" +
            "fjxrtdavnmgiyoeuzslhk\n" +
            "glotsukjrfyahmeizn\n" +
            "\n" +
            "fgvzuiksxlptcqwmnohr\n" +
            "oqztcmspnhwvijkdgu\n" +
            "\n" +
            "whfx\n" +
            "kfh\n" +
            "hfr\n" +
            "bnjzhsdfi\n" +
            "ufqch\n" +
            "\n" +
            "ncbfhpexm\n" +
            "xremnpfc\n" +
            "bencmpxfw\n" +
            "\n" +
            "rpyknb\n" +
            "ktpcb\n" +
            "cpzkb\n" +
            "\n" +
            "beou\n" +
            "uej\n" +
            "\n" +
            "qgyudcrhfml\n" +
            "pvkjzneo\n" +
            "\n" +
            "azosqblkfdjuipemwygr\n" +
            "nxqjumytrglaohsidp\n" +
            "uoamsqgyrjdiplx\n" +
            "dlumpoyarsgjqci\n" +
            "\n" +
            "pkbhegfducs\n" +
            "sukehcfbtjdg\n" +
            "\n" +
            "qfjm\n" +
            "qkselfmob\n" +
            "qfcxnvm\n" +
            "jmqwf\n" +
            "mfq\n" +
            "\n" +
            "ivmpywfqruhs\n" +
            "rupmfhqiyswv\n" +
            "\n" +
            "dkav\n" +
            "vadk\n" +
            "kvda\n" +
            "\n" +
            "kincpbv\n" +
            "cknuv\n" +
            "vnuckxag\n" +
            "\n" +
            "flhdeonaxsciv\n" +
            "descoflahnvix\n" +
            "nofiacdvhxsel\n" +
            "ehlfoisvxcnda\n" +
            "\n" +
            "hs\n" +
            "ztedwx\n" +
            "nlva\n" +
            "\n" +
            "meqycx\n" +
            "cqmiye\n" +
            "qgmotyce\n" +
            "mcqgye\n" +
            "emcqy\n" +
            "\n" +
            "dwshy\n" +
            "swhyd\n" +
            "hwyds\n" +
            "swyhd\n" +
            "\n" +
            "wbqvtxal\n" +
            "\n" +
            "tlfdbvkyu\n" +
            "flydbk\n" +
            "bsrpfidqxky\n" +
            "\n" +
            "unwtfcv\n" +
            "kvrfbnw\n" +
            "\n" +
            "xazgi\n" +
            "agz\n" +
            "ysga\n" +
            "nawgv\n" +
            "\n" +
            "swtx\n" +
            "gnqayohzm\n" +
            "\n" +
            "un\n" +
            "z\n" +
            "\n" +
            "tr\n" +
            "g\n" +
            "g\n" +
            "d\n" +
            "k\n" +
            "\n" +
            "dl\n" +
            "tl\n" +
            "dl\n" +
            "\n" +
            "v\n" +
            "youdan\n" +
            "ejm\n" +
            "\n" +
            "arktbdczqfvx\n" +
            "qtzxbdkarfcv\n" +
            "\n" +
            "gfve\n" +
            "vefkg\n" +
            "\n" +
            "emojkagtqclzxdf\n" +
            "jtamfedbocz\n" +
            "hzpijrveasomwdfcyt\n" +
            "metazdkcjfulo\n" +
            "\n" +
            "uplwm\n" +
            "pwulm\n" +
            "cmwup\n" +
            "wupm\n" +
            "umwp\n" +
            "\n" +
            "apjeybkdmq\n" +
            "kdjqpmyea\n" +
            "\n" +
            "k\n" +
            "k\n" +
            "i\n" +
            "k\n" +
            "eng\n" +
            "\n" +
            "w\n" +
            "wh\n" +
            "f\n" +
            "j\n" +
            "\n" +
            "rykcomu\n" +
            "mcyorxuk\n" +
            "muoyrck\n" +
            "rcoykmu\n" +
            "yukocrm\n" +
            "\n" +
            "uc\n" +
            "mcn\n" +
            "sfl\n" +
            "exqazjb\n" +
            "vdc\n" +
            "\n" +
            "hpoack\n" +
            "cltek\n" +
            "\n" +
            "esjqog\n" +
            "qeso\n" +
            "seqo\n" +
            "qesoy\n" +
            "eqos\n" +
            "\n" +
            "d\n" +
            "o\n" +
            "v\n" +
            "ag\n" +
            "\n" +
            "rnzgaehid\n" +
            "parned\n" +
            "dnaefr\n" +
            "pdrnyake\n" +
            "sernad\n" +
            "\n" +
            "xzhlvcnjykdmp\n" +
            "zlvxihpwjkyn\n" +
            "yzklnvxhgqjp\n" +
            "\n" +
            "v\n" +
            "v\n" +
            "vt\n" +
            "v\n" +
            "\n" +
            "ksmfiwl\n" +
            "mklsfwi\n" +
            "sfkmwli\n" +
            "ifkswlm\n" +
            "imlsfwk\n" +
            "\n" +
            "nzogsphkcw\n" +
            "hkgpowzcbsn\n" +
            "gowhkscpnjxz\n" +
            "hspwckgzon\n" +
            "\n" +
            "kqoxpyvzuw\n" +
            "lorghcfmjte\n" +
            "\n" +
            "uldnticjqhrzwmx\n" +
            "mnwuqclgzpjrske\n" +
            "lfcynwrvmzjuqa\n" +
            "lhnomxjzuqgcwr\n" +
            "\n" +
            "tdpxnfrj\n" +
            "txpjdr\n" +
            "ptjrdx\n" +
            "dxjtrp\n" +
            "rdpxtjb\n" +
            "\n" +
            "zfaeqorn\n" +
            "qmezdfxr\n" +
            "uqbyeizphrgtjsk\n" +
            "\n" +
            "ghizjpctfdnql\n" +
            "rvoaecnykifdtp\n" +
            "\n" +
            "liszmpruehocfndgt\n" +
            "bdiruxnsfplkgoe\n" +
            "\n" +
            "mzvcwhrqabpnstxjyoleifd\n" +
            "mbwtcxlzosyeqpvfdinajrh\n" +
            "hqenawizmxyjvlrptbcdsfo\n" +
            "tzovqajmwdsepcyflhrxbin\n" +
            "\n" +
            "ehodx\n" +
            "svycbltpmoa\n" +
            "irohkxe\n" +
            "fzjuo\n" +
            "\n" +
            "rv\n" +
            "rv\n" +
            "rv\n" +
            "vr\n" +
            "vr\n" +
            "\n" +
            "axoez\n" +
            "zoexa\n" +
            "xozae\n" +
            "aoxze\n" +
            "zoaex\n" +
            "\n" +
            "vmgthlaxsnbidk\n" +
            "nqtzilcrhgsjauxm\n" +
            "\n" +
            "oahz\n" +
            "hzqaoc\n" +
            "ohaz\n" +
            "hezao\n" +
            "\n" +
            "obkwvazgc\n" +
            "kvsaegcopnwbdz\n" +
            "zgkbwvoac\n" +
            "kzgawbovc\n" +
            "cgoakzbvwl\n" +
            "\n" +
            "klnmgi\n" +
            "mciln\n" +
            "scnpi\n" +
            "yniw\n" +
            "\n" +
            "ekwcfunhsba\n" +
            "sjuhcnfeakb\n" +
            "sbefhaqkucn\n" +
            "kaoudnferscbhy\n" +
            "\n" +
            "ebcoplsnuw\n" +
            "camnjlepubo\n" +
            "lsoebcnupz\n" +
            "\n" +
            "tfxyvgznocdleb\n" +
            "tihbfsn\n" +
            "tnfhbp\n" +
            "\n" +
            "eyojwm\n" +
            "yjomex\n" +
            "mjeyo\n" +
            "\n" +
            "wpvtdjzrcf\n" +
            "xmfuncgiybjhpsqlkz\n" +
            "\n" +
            "tzcwnlei\n" +
            "twceinl\n" +
            "inlcvgtkew\n" +
            "ilcwxetn\n" +
            "ncmwtaiel\n" +
            "\n" +
            "hzwocd\n" +
            "qvhkn\n" +
            "hytliebm\n" +
            "fshq\n" +
            "\n" +
            "sxlbnowmv\n" +
            "msonwxb\n" +
            "\n" +
            "hdknsxog\n" +
            "nfojk\n" +
            "avelwctzqmripuy\n" +
            "\n" +
            "slgrm\n" +
            "msrgl\n" +
            "glsrm\n" +
            "\n" +
            "shjieplz\n" +
            "zogimjcv\n" +
            "rkfqxdynwbu\n" +
            "\n" +
            "oejgdcamtxzhyn\n" +
            "jhcntdealyzxogq\n" +
            "ejthagzcxonyd\n" +
            "onxdjsmycgztaeh\n" +
            "\n" +
            "uyloghq\n" +
            "yguhlqro\n" +
            "uoyqlgh\n" +
            "ouyhqgl\n" +
            "yoluqhg\n" +
            "\n" +
            "oxqtmpjzieunbdak\n" +
            "nlmhzwjedxouyisctfpvrg\n" +
            "\n" +
            "kmrnhzcad\n" +
            "ahzrcndm\n" +
            "\n" +
            "sbcmuhfkanitw\n" +
            "scbkmaftwhdinu\n" +
            "swmbkhnacitfu\n" +
            "ntcaukbwmshif\n" +
            "kswhbufimctna\n" +
            "\n" +
            "nlhwqxvpjgmsr\n" +
            "rvgmyjxhsplaqewn\n" +
            "smvnlwgqxrphj\n" +
            "qjnxpmlwhrsvg\n" +
            "lmsjpqrwnxhgv\n" +
            "\n" +
            "fivwsrdz\n" +
            "ekcq\n" +
            "xg\n" +
            "\n" +
            "umhborsxcg\n" +
            "bghsmqxuc\n" +
            "\n" +
            "jwnv\n" +
            "wjnv\n" +
            "vnjw\n" +
            "vwjn\n" +
            "wlvnj\n" +
            "\n" +
            "vlfhdjz\n" +
            "hjlzdvf\n" +
            "dozvmlhfj\n" +
            "jlhvzfd\n" +
            "\n" +
            "fue\n" +
            "ksmad\n" +
            "l\n" +
            "\n" +
            "wcjsaepudqvionrt\n" +
            "rlhydbgixmznkcjt\n" +
            "\n" +
            "cqh\n" +
            "qc\n" +
            "cql\n" +
            "qc\n" +
            "\n" +
            "kwapzcyisfexgmolnhbrqv\n" +
            "vfdlyxsmkotwhbpziraqcg\n" +
            "\n" +
            "ctmgd\n" +
            "gtdm\n" +
            "\n" +
            "xwornpgqkmizhutfdlb\n" +
            "nzdjoiwprvhtflkcgum\n" +
            "trigoqlwhzmkpdufn\n" +
            "\n" +
            "nix\n" +
            "xni\n" +
            "nxi\n" +
            "\n" +
            "nrvcsp\n" +
            "fjbkd\n" +
            "\n" +
            "fvdmgq\n" +
            "fqdmvg\n" +
            "mvqfgd\n" +
            "\n" +
            "blx\n" +
            "x\n" +
            "tv\n" +
            "rkqzge\n" +
            "l\n" +
            "\n" +
            "j\n" +
            "d\n" +
            "uc\n" +
            "f\n" +
            "j\n" +
            "\n" +
            "mnqbwykj\n" +
            "nksfmwtbzepi\n" +
            "mndjkwrqb\n" +
            "dbkwnm\n" +
            "\n" +
            "eskvjnozwclrumqgiydhpat\n" +
            "zptyjudvmlaehnqoiscgrwk\n" +
            "epgmahlktynjdsvouqizwcr\n" +
            "mnltkagqcxwyveidsourjzph\n" +
            "dpmjiovtqswrzluhknyegca\n" +
            "\n" +
            "wd\n" +
            "ws\n" +
            "dhw\n" +
            "\n" +
            "hcs\n" +
            "shc\n" +
            "hcs\n" +
            "chs\n" +
            "sch\n" +
            "\n" +
            "fsajcbywgh\n" +
            "fougyesbrcahjv\n" +
            "bfhsjyagc\n" +
            "hfacgbsjy\n" +
            "yjagcsbhf\n" +
            "\n" +
            "ymnkoucts\n" +
            "sykmzotc\n" +
            "ouyktsmc\n" +
            "\n" +
            "v\n" +
            "tv\n" +
            "v\n" +
            "v\n" +
            "vbf\n" +
            "\n" +
            "uxplo\n" +
            "upxl\n" +
            "lxpu\n" +
            "cunlxp\n" +
            "lpux\n" +
            "\n" +
            "bclgqmi\n" +
            "ibmlcg\n" +
            "mlibgcan\n" +
            "ligmcb\n" +
            "\n" +
            "je\n" +
            "kje\n" +
            "ecnhi\n" +
            "jye\n" +
            "\n" +
            "xoy\n" +
            "yxo\n" +
            "oyx\n" +
            "\n" +
            "tdkglesr\n" +
            "pqkrhevxulo\n" +
            "rzsyetlakd\n" +
            "\n" +
            "gauz\n" +
            "zuag\n" +
            "zagu\n" +
            "zgau\n" +
            "zgua\n" +
            "\n" +
            "vsph\n" +
            "huspgvl\n" +
            "vpksh\n" +
            "puhvg\n" +
            "ahmpivodq\n" +
            "\n" +
            "uewjqlcdghxszbr\n" +
            "ntrxwsljz\n" +
            "lrojxkfaszw\n" +
            "zjfipyxslwrv\n" +
            "\n" +
            "dqkswrctf\n" +
            "svwfebmkdrzpyqjx\n" +
            "rdswgqnfklt\n" +
            "\n" +
            "njwzbhkfilvec\n" +
            "nvjcelwhbgfz\n" +
            "efcwlhbxvzjn\n" +
            "sefbhpljwzcvn\n" +
            "nljfcvzwexhb\n" +
            "\n" +
            "tiflgjea\n" +
            "ogjfaqvitl\n" +
            "\n" +
            "avrklgztmw\n" +
            "mzwegvnkatlq\n" +
            "vmtlakzgw\n" +
            "magtzklfibwv\n" +
            "vlaetnzkugwm\n" +
            "\n" +
            "vfa\n" +
            "atvf\n" +
            "fva\n" +
            "\n" +
            "pgxnohyielrtdbzk\n" +
            "txfhrpyoedkgmn\n" +
            "\n" +
            "cry\n" +
            "cry\n" +
            "ycr\n" +
            "\n" +
            "sqogwpir\n" +
            "irdoqxwpge\n" +
            "gqrywipo\n" +
            "pdwijgqor\n" +
            "gfvobipwqmlr\n" +
            "\n" +
            "mb\n" +
            "bzm\n" +
            "z\n" +
            "q\n" +
            "\n" +
            "bgowltrfchp\n" +
            "gbhlopctfrw\n" +
            "rpohbwlcfgstax\n" +
            "\n" +
            "gquyvhfizapblmdcnkewx\n" +
            "mwsukfhcqbglexiavznyd\n" +
            "iefbqnxvwlzmkuhcaydg\n" +
            "\n" +
            "wctkbxhpv\n" +
            "ladpwgrzovshmt\n" +
            "untwvihp\n" +
            "etjwqphv\n" +
            "yvptwfh\n" +
            "\n" +
            "eqsyvjwfctgplhxabzr\n" +
            "munwkdibo\n" +
            "\n" +
            "dqlbhkcwzrsmtpi\n" +
            "wklrtmsdczhabipq\n" +
            "\n" +
            "qhesvmjdyxw\n" +
            "ivqetudjb\n" +
            "javdteq\n" +
            "joqdve\n" +
            "\n" +
            "krdltagi\n" +
            "pcgqmxje\n" +
            "fgmb\n" +
            "\n" +
            "olxaykprm\n" +
            "mpylsaxr\n" +
            "\n" +
            "wm\n" +
            "j\n" +
            "j\n" +
            "j\n" +
            "\n" +
            "fkcogpsdjbhmrlixwya\n" +
            "dxozrtmjsycpiwbelqgf\n" +
            "wgunpmldzxfeoiycsrbj\n" +
            "locvwxgfjmsbtypdir\n" +
            "\n" +
            "ek\n" +
            "ke\n" +
            "ek\n" +
            "\n" +
            "jxsczemidvof\n" +
            "ovfmdzicjxse\n" +
            "edovzsmcxjif\n" +
            "exfomdzvcjis\n" +
            "\n" +
            "bovesgqckmlnzd\n" +
            "lozkvnegbmchsqd\n" +
            "kglnesdvqobzcm\n" +
            "\n" +
            "iynrwcudgzpvmbhkl\n" +
            "phybgwrjiznlavudc\n" +
            "\n" +
            "inhflg\n" +
            "lghnfqis\n" +
            "hrlxfngi\n" +
            "ghinakwflyu\n" +
            "ltrnhbigf\n" +
            "\n" +
            "eij\n" +
            "luej\n" +
            "wcjep\n" +
            "\n" +
            "cmbwja\n" +
            "macrbwg\n" +
            "\n" +
            "gbnaxskwovjhqtyf\n" +
            "nhofbspvktwqz\n" +
            "\n" +
            "pmq\n" +
            "s\n" +
            "c\n" +
            "j\n" +
            "vs\n" +
            "\n" +
            "t\n" +
            "ty\n" +
            "tn\n" +
            "\n" +
            "glxsy\n" +
            "yskixgjld\n" +
            "bswalux\n" +
            "nxjls\n" +
            "\n" +
            "vueh\n" +
            "uevh\n" +
            "\n" +
            "mjvlyedipz\n" +
            "mvzdjeiwry\n" +
            "mevizodyj\n" +
            "\n" +
            "brhntfpvglmo\n" +
            "cmzvt\n" +
            "viamct\n" +
            "\n" +
            "ymbviloeqth\n" +
            "hkltyqcmoxudjnb\n" +
            "bwqzmpytolh\n" +
            "movehlytbwqi\n" +
            "\n" +
            "lbdqjzrfayh\n" +
            "afgdebjthyl\n" +
            "hdkjbalfyu\n" +
            "\n" +
            "yv\n" +
            "gv\n" +
            "v\n" +
            "\n" +
            "dxyqclmgvpahor\n" +
            "ktjmr\n" +
            "zbwfnrm\n" +
            "mtzewjr\n" +
            "rmsui\n" +
            "\n" +
            "ghksqe\n" +
            "nlerhxqkmsvo\n" +
            "qekshg\n" +
            "heksqg\n" +
            "qsgyhke\n" +
            "\n" +
            "jecfapg\n" +
            "asgpmjnfw\n" +
            "\n" +
            "lshjykoirpuzcgmwdqv\n" +
            "qwgzoudypclsvrhimjk\n" +
            "drmjwylhqvpigcsuzok\n" +
            "\n" +
            "poclyq\n" +
            "lpoycq\n" +
            "\n" +
            "wsfcn\n" +
            "cisz\n" +
            "\n" +
            "o\n" +
            "d\n" +
            "o\n" +
            "o\n" +
            "o\n" +
            "\n" +
            "goqubkareptcj\n" +
            "mkrcebtspaj\n" +
            "pkbjracte\n" +
            "\n" +
            "lcwvagpbzi\n" +
            "lwgap\n" +
            "lwgpax\n" +
            "\n" +
            "nmxilaeurpkbcqt\n" +
            "excklrinuatyqpb\n" +
            "oxzrbcnqlgtapiuwe\n" +
            "qbtodxcnreuail\n" +
            "fqevniubrjclstaxh\n" +
            "\n" +
            "kbqclfmnrowuzh\n" +
            "cromfwbznhkluq\n" +
            "cfrunokbmhzlqw\n" +
            "ucmfbnwkolzqhr\n" +
            "lcunfhmzkboqrw\n" +
            "\n" +
            "zabujhtvnkiwlprse\n" +
            "rwbxgszjhfdotvinpela\n" +
            "ivptyewzmhdcnjalsbqr\n" +
            "\n" +
            "m\n" +
            "mocztn\n" +
            "\n" +
            "docyu\n" +
            "uzdocmy\n" +
            "ocfsdyrut\n" +
            "\n" +
            "n\n" +
            "n\n" +
            "n\n" +
            "ng\n" +
            "\n" +
            "zntxuekvgasqjbhdcpywir\n" +
            "bzpakvruhewjqiycdgtxsn\n" +
            "dwgubaxqkvepizsnjrcyth\n" +
            "sthxpekqviydwazujgrbcn\n" +
            "\n" +
            "e\n" +
            "ke\n" +
            "ydv\n" +
            "e\n" +
            "k\n" +
            "\n" +
            "ausdlnoefwzyrxbqmjiv\n" +
            "hrsizvqnwmejofabguxld\n" +
            "edmfjzlvoinxyqprwaus\n" +
            "ievajdrlfkzqcstnouxwm\n" +
            "\n" +
            "dkxoaplqsbz\n" +
            "zdrxpfltkobywasq\n" +
            "\n" +
            "hpcniyojgsztdlub\n" +
            "litbsnghpojcyzdu\n" +
            "jdhbycapzuwgtnlsio\n" +
            "hbsiltzyudcpngjo\n" +
            "\n" +
            "jkbog\n" +
            "uvgok\n" +
            "vog\n" +
            "xgieom\n" +
            "\n" +
            "f\n" +
            "y\n" +
            "y\n" +
            "\n" +
            "zoswvb\n" +
            "swgbzdvot\n" +
            "wsrezbvoc\n" +
            "\n" +
            "gdutplihzvfocxa\n" +
            "zpqonktlyrucaidmfvh\n" +
            "tuavsxdhfozlgciebjpw\n" +
            "\n" +
            "htydg\n" +
            "tlg\n" +
            "meygtd\n" +
            "tqjrg\n" +
            "\n" +
            "zhugty\n" +
            "tzghy\n" +
            "ezysgth\n" +
            "\n" +
            "eirgsfbqmhoxkyj\n" +
            "wkhfsoeibmjgqyxr\n" +
            "qgokmyxeishjrfb\n" +
            "dfbsuriyjogeqvhxmk\n" +
            "\n" +
            "u\n" +
            "ubi\n" +
            "u\n" +
            "u\n" +
            "u\n" +
            "\n" +
            "cvseaypi\n" +
            "iycpve\n" +
            "pveiyc\n" +
            "ivycpe\n" +
            "\n" +
            "ojgxqrzpf\n" +
            "qfzrgoijxp\n" +
            "qojgrxfzp\n" +
            "gropqxjzf\n" +
            "jrgxfqzpo\n" +
            "\n" +
            "oswduz\n" +
            "ozuswd\n" +
            "wozusd\n" +
            "wosdzu\n" +
            "\n" +
            "zepyf\n" +
            "wpe\n" +
            "dep\n" +
            "\n" +
            "ptsoviyubhefwdg\n" +
            "eugbfwotdvspy\n" +
            "dabcyetvufgpos\n" +
            "\n" +
            "gvwjbspykdzoarinteh\n" +
            "hjrecqndygmabifp\n" +
            "\n" +
            "belwimkrtvhnzojau\n" +
            "nvaqblwkreohsmtcz\n" +
            "ovaxdmgnzbeykrtlhw\n" +
            "kwzorvhnbplqtema\n" +
            "\n" +
            "yskfpmjebdich\n" +
            "exzjvwsbipomqr\n" +
            "ijsbutamfheldpc\n" +
            "\n" +
            "xowyihcmreuqldkjgv\n" +
            "ymqlrhduocepkzijxwv\n" +
            "wdyljroqshcvfekbmuitxz\n" +
            "eiolxkjvqcwmuyhard\n" +
            "\n" +
            "rifsactz\n" +
            "dtrlaspjefbicozn\n" +
            "wfizahcvrqkts\n" +
            "vmtfyhqacirszg\n" +
            "\n" +
            "jgbdalcpw\n" +
            "putak\n" +
            "dzacrwop\n" +
            "gopadq\n" +
            "\n" +
            "scotnlhavpyjqmfgzk\n" +
            "ygtocpjnzfvmlkqa\n" +
            "qcjlytnkfozvmpag\n" +
            "\n" +
            "iu\n" +
            "bu\n" +
            "dul\n" +
            "u\n" +
            "u\n" +
            "\n" +
            "gadyx\n" +
            "jti\n" +
            "\n" +
            "f\n" +
            "f\n" +
            "\n" +
            "da\n" +
            "pxa\n" +
            "\n" +
            "mgbskecwd\n" +
            "wgcktmse\n" +
            "sgecmtkw\n" +
            "cekbwsmdg\n" +
            "saegcfvkwm\n" +
            "\n" +
            "jm\n" +
            "mj\n" +
            "mj\n" +
            "kmj\n" +
            "mj\n" +
            "\n" +
            "bdkzv\n" +
            "ftloezbkdvy\n" +
            "zbvxdk\n" +
            "bzwkdv\n" +
            "vkdbszu\n" +
            "\n" +
            "btkesqymhzuwcpd\n" +
            "tcaiwjxsg\n" +
            "wsct\n" +
            "tinwcs\n" +
            "\n" +
            "amqgrkjsv\n" +
            "jsgmqzakro\n" +
            "aksmqgjr\n" +
            "arkmgsqj\n" +
            "graqjmsk\n" +
            "\n" +
            "vwbjpyehxfrcguzlit\n" +
            "efskqzadontm\n" +
            "\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "mnos\n" +
            "jdvsnfomx\n" +
            "aosnm\n" +
            "\n" +
            "zoh\n" +
            "znoh\n" +
            "ohf\n" +
            "kdhto\n" +
            "\n" +
            "zb\n" +
            "bzn\n" +
            "jzb\n" +
            "jzb\n" +
            "zbj\n" +
            "\n" +
            "jomtfxgs\n" +
            "nkqytilrace\n" +
            "\n" +
            "mzkberyufodx\n" +
            "ujnpckbhxroz\n" +
            "lkbxorzui\n" +
            "uqozrcjbkx\n" +
            "zorbxuik\n" +
            "\n" +
            "hklmwxyvtdcpgoq\n" +
            "vjgpxqaohmdlwktc\n" +
            "xftwhlpvkqgdmoc\n" +
            "xqdpotmvhfylcwgk\n" +
            "\n" +
            "ocu\n" +
            "cou\n" +
            "cou\n" +
            "\n" +
            "ijanryulhzg\n" +
            "ujainhlszgr\n" +
            "lagnhrizjk\n" +
            "ahnrbdgizjlv\n" +
            "\n" +
            "vdnce\n" +
            "dcqne\n" +
            "dnejc\n" +
            "nectd\n" +
            "\n" +
            "eifwmbdut\n" +
            "mdftwiube\n" +
            "tuinmwfdbe\n" +
            "mfdwitbeu\n" +
            "\n" +
            "ipsbgk\n" +
            "jsai\n" +
            "\n" +
            "sqtucpvhbimroydkfjxlaz\n" +
            "azmdqcrefjyubkwhsotpv\n" +
            "\n" +
            "ygczbjvlrnk\n" +
            "lgjivzc\n" +
            "clsgpvdzjqm\n" +
            "ohjvzlmcg\n" +
            "\n" +
            "savmyfxg\n" +
            "xeyfsmag\n" +
            "qmsxgyfrw\n" +
            "xvfkmgyahs\n" +
            "\n" +
            "ynzsbet\n" +
            "bsrtnzv\n" +
            "bdjwzhamfnqk\n" +
            "nzbciex\n" +
            "nobzgvps\n" +
            "\n" +
            "gjmaqcdiebhupywzfltvko\n" +
            "ktqibcuvalsmnghefyprdoj\n" +
            "\n" +
            "mvqwdhflazokj\n" +
            "okfqwvdmelhzaj\n" +
            "zvjwacmuloqiskgtdyh\n" +
            "flnpwzxvhqjdmroka\n" +
            "qzmoalwkhpvjd\n" +
            "\n" +
            "n\n" +
            "h\n" +
            "th\n" +
            "fsoxd\n" +
            "\n" +
            "peqynb\n" +
            "qepbyw\n" +
            "qeprby\n" +
            "bpqayvel\n" +
            "qyabpe\n" +
            "\n" +
            "sykhfvwmgnutbeadql\n" +
            "gtkmuflbndvwhsyeaqc\n" +
            "djwftvybqumneskhgal\n" +
            "skwtqbzrmhegulanydvfi\n" +
            "\n" +
            "fuz\n" +
            "fuz\n" +
            "uzf\n" +
            "uzfx\n" +
            "zuf\n" +
            "\n" +
            "yrpkxfnzbmgqwvsluoa\n" +
            "psyulngqwrazvkfxemo\n" +
            "pmqwxayzobklrugnfevs\n" +
            "xrgqnsivfpwazlkuoym\n" +
            "jsglfrdaqvomxypzwknu\n" +
            "\n" +
            "arm\n" +
            "rnhamv\n" +
            "tlabjmx\n" +
            "\n" +
            "rxpzbehywfuts\n" +
            "xruyvzwbmsef\n" +
            "ryebwfqgsuxz\n" +
            "zsrxbeuwyf\n" +
            "\n" +
            "bufrwlvodngkmxitpha\n" +
            "loufnmdtqrkabghxiwvep\n" +
            "hdutjkmafzxnrgvowpbil\n" +
            "kxuphaodvbirwfmtlgn\n" +
            "\n" +
            "hgdeptiafxsujklr\n" +
            "dskupraelhxtfivgj\n" +
            "tuegfxjshdkprlia\n" +
            "\n" +
            "ejsbfhcvnx\n" +
            "frtecbvxnjszh\n" +
            "\n" +
            "iouylrj\n" +
            "uojlxyri\n" +
            "fyuoikjlrm\n" +
            "\n" +
            "bteiydmrh\n" +
            "edmairhwftb\n" +
            "\n" +
            "iygeubcal\n" +
            "biycheplzagu\n" +
            "\n" +
            "xnpmz\n" +
            "ycnmzpbdq\n" +
            "zmnpk\n" +
            "pnzm\n" +
            "pnzm\n" +
            "\n" +
            "wzlhmaoq\n" +
            "wafiyomc\n" +
            "ptgawvoer\n" +
            "\n" +
            "tpynexdwkolrfhqj\n" +
            "hlnprfxoytqwdjek\n" +
            "qxwkortdnyfhljpe\n" +
            "wnqkjyfxdlohpret\n" +
            "\n" +
            "psjucnhrbefvzyl\n" +
            "dnwzqmauglcti\n" +
            "zqudiclnk\n" +
            "\n" +
            "sg\n" +
            "sg\n" +
            "gs\n" +
            "\n" +
            "phbydkeljnzaow\n" +
            "ajnkzbcige\n" +
            "eakbjrcqxnz\n" +
            "\n" +
            "sjcdoehzu\n" +
            "ceuoshdjz\n" +
            "djocseuzh\n" +
            "\n" +
            "nkxlgspidmhwzqeojv\n" +
            "fnhwxuiktzmjogqvdl\n" +
            "\n" +
            "doirbfxv\n" +
            "oxysdbufri\n" +
            "dboixvf\n" +
            "ifndxob\n" +
            "moixzdfbj\n" +
            "\n" +
            "dtbmegpvux\n" +
            "nlhcjayz\n" +
            "onjfrsqkw\n" +
            "\n" +
            "lqpamhfudgjtv\n" +
            "lgjudvhfqtpam\n" +
            "vtaglfumdhqpj\n" +
            "\n" +
            "z\n" +
            "iz\n" +
            "z\n" +
            "z\n" +
            "\n" +
            "dewlyguxtivcqb\n" +
            "xleqbcitgvduwy\n" +
            "lbtwegqkcivdxshyu\n" +
            "\n" +
            "yrxqbsonfcui\n" +
            "oszafcntugd\n" +
            "\n" +
            "obke\n" +
            "kbeo\n" +
            "ebok\n" +
            "obek\n" +
            "eobk\n" +
            "\n" +
            "wtoxd\n" +
            "odxwt\n" +
            "odwtx\n" +
            "\n" +
            "kndxiqheltrpacwbu\n" +
            "idekwaovchjpxrtbunql\n" +
            "builrdxnpcehtjwsqa\n" +
            "iuabpznqrlhfdtemycxw\n" +
            "ebrxiuaqpclkdwgtnh\n" +
            "\n" +
            "itvghlycjnz\n" +
            "hyjltiznvg\n" +
            "wnjzmklhvgity\n" +
            "bhyizgtjvnl\n" +
            "gnjviylzth\n" +
            "\n" +
            "jzp\n" +
            "uki\n" +
            "revlhqgayn\n" +
            "fsjt\n" +
            "biw\n" +
            "\n" +
            "yadxckevlw\n" +
            "wlkcvydx\n" +
            "xkdwvlyc\n" +
            "\n" +
            "xqsw\n" +
            "qsxw\n" +
            "sxwq\n" +
            "qxws\n" +
            "wsqxf\n" +
            "\n" +
            "dmqyrznsoifej\n" +
            "wyge\n" +
            "gktlabye\n" +
            "\n" +
            "rnyqsv\n" +
            "nqsrvjy\n" +
            "\n" +
            "zuw\n" +
            "z\n" +
            "\n" +
            "fawqurvtmopkc\n" +
            "kcmquvwptfoa\n" +
            "komcuavqtwpf\n" +
            "uaovkwpqfcmjt\n" +
            "ocmwvfupqakt\n" +
            "\n" +
            "ztlsuyribvogcpme\n" +
            "ouvmrltbescizypg\n" +
            "gmsvutbeoylricpz\n" +
            "zmgticyleusobprv\n" +
            "\n" +
            "pfhniyksrwcvduqogat\n" +
            "knfgaviyqrcusodh\n" +
            "rukvogciqfandsyh\n" +
            "fkacsgyqdoivurhn\n" +
            "\n" +
            "q\n" +
            "e\n" +
            "m\n" +
            "\n" +
            "cbr\n" +
            "rbc\n" +
            "brc\n" +
            "rbc\n" +
            "brc\n" +
            "\n" +
            "zlps\n" +
            "zpsl\n" +
            "spzl\n" +
            "zjlps\n" +
            "zlsp\n" +
            "\n" +
            "zvi\n" +
            "v\n" +
            "\n" +
            "skfw\n" +
            "sw\n" +
            "\n" +
            "tuygxsjhiczeapmbvwkqn\n" +
            "tenjiavpshbyckwmqzugx\n" +
            "gtsqkmneacvbzdjophuixw\n" +
            "\n" +
            "tbl\n" +
            "lsyzjmcg\n" +
            "\n" +
            "ntofwi\n" +
            "tnofi\n" +
            "itjeofn\n" +
            "\n" +
            "o\n" +
            "l\n" +
            "l\n" +
            "\n" +
            "qoaujcnksbpiwgtheryvfxmlz\n" +
            "anvhyiscfoekqupglxrzdtmjb\n" +
            "lxscnzkqofbyeuvtmrhgiapj\n" +
            "\n" +
            "rakhwzxtclnymgbsiej\n" +
            "rcustiyeagmnxbzkhwl\n" +
            "bnfrtwslzyhcexqkamig\n" +
            "\n" +
            "tbo\n" +
            "tbevu\n" +
            "bt\n" +
            "\n" +
            "zfkgeyjmuplqsrxdbwtvhconia\n" +
            "bremfqgkdlvsuyxazwpntocjhi\n" +
            "jbimlwsznaktxhvrfoygcepuqd\n" +
            "jaedlpixsfomuhgwqrzctbyvkn\n" +
            "\n" +
            "bqskzjafrehwu\n" +
            "akwsjufzebqh\n" +
            "\n" +
            "eqfmkpjztwrxhugbyn\n" +
            "ghrbtmfuqypexjkwnz\n" +
            "ebptfnqxhryujwmkzg\n" +
            "juzewkctxqlfmhpygbrn\n" +
            "tbhrgmyfxqnkuzpwej\n" +
            "\n" +
            "afqpvgjxehwdo\n" +
            "jgzbeafwdophvx\n" +
            "xkaesfvdhpjgmow\n" +
            "zhpuveldxwgfqjao\n" +
            "xjzadovrepfhgwy\n" +
            "\n" +
            "hzfwtimqxyl\n" +
            "wfylhxtqzmi\n" +
            "qtxfhzwlimy\n" +
            "thimxwlfyqz\n" +
            "\n" +
            "gyikxanutzjvrhod\n" +
            "xedlmbopwfcrtnyjsazq\n" +
            "\n" +
            "yhznowsvmiplc\n" +
            "lyizcvohsnxmw\n" +
            "nywacvmirfbzlsgh\n" +
            "sczlmwynivh\n" +
            "\n" +
            "xbjzeyamohuftwirpl\n" +
            "yqwgjurichlevfbz\n" +
            "\n" +
            "grzilwbosadunexh\n" +
            "zswunredgtaobkhxpl\n" +
            "\n" +
            "hpqsuokcydmwl\n" +
            "inewxzrg\n" +
            "zwvjb\n" +
            "wg\n" +
            "watr\n" +
            "\n" +
            "hdkjnms\n" +
            "bmdhjscnk\n" +
            "xsijavqmoklpf\n" +
            "\n" +
            "jelhuczo\n" +
            "xpojuhlbqzrt\n" +
            "\n" +
            "orkbs\n" +
            "cbs\n" +
            "mxdbij\n" +
            "br\n" +
            "\n" +
            "mkpna\n" +
            "kapn\n" +
            "pnak\n" +
            "\n" +
            "rpdw\n" +
            "pwdr\n" +
            "\n" +
            "qc\n" +
            "qc\n" +
            "cq\n" +
            "cq\n" +
            "qch\n" +
            "\n" +
            "umqepd\n" +
            "ceapd\n" +
            "xqdpelh\n" +
            "pukedf\n" +
            "\n" +
            "vfkdrqcbumxoian\n" +
            "cnwmukjvqrbodai\n" +
            "\n" +
            "tbeizdphysfxwrlaokuq\n" +
            "ywzaqsprukdtbheoxil\n" +
            "rvkieodhtqsupywxcazl\n" +
            "hsdiwzeqoryulpktax\n" +
            "axoqulrigtnwehsdkzypm\n" +
            "\n" +
            "gvfkhzwtlm\n" +
            "zrsmwnbuie\n" +
            "\n" +
            "zrxtwfnqod\n" +
            "fvloabkyirwzmn\n" +
            "\n" +
            "iltbsmy\n" +
            "tliybms\n" +
            "bylsitm\n" +
            "\n" +
            "k\n" +
            "g\n" +
            "voh\n" +
            "pm\n" +
            "\n" +
            "yrdneovzfghxalmspuckt\n" +
            "tqnikyerogxuhmfvpzla\n" +
            "\n" +
            "ylckwbrtmsjv\n" +
            "tkjlvcqrfea\n" +
            "\n" +
            "twjumlapesnz\n" +
            "pmeoazub\n" +
            "pmabuoez\n" +
            "\n" +
            "xmgyd\n" +
            "xdymg\n" +
            "dxygm\n" +
            "dgymx\n" +
            "gxudcvmy\n" +
            "\n" +
            "v\n" +
            "vw\n" +
            "pvd\n" +
            "vu\n" +
            "v\n" +
            "\n" +
            "qwmfrncxb\n" +
            "drjqglsakpwtbi\n";

    static boolean validIntRange(String text, int lowerBound, int upperBound) {
        try {
            int value = Integer.parseInt(text);
            return value >= lowerBound && value <= upperBound;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private static class LineSupplier implements Supplier<String> {
        final Scanner in;

        public LineSupplier(Scanner in) {
            this.in = in;
        }

        @Override
        public String get() {
            return in.hasNext()
                    ? in.nextLine()
                    : null;
        }
    }

    private static class BatchSupplier implements Supplier<String> {
        final Scanner in;

        public BatchSupplier(Scanner in) {
            this.in = in;
        }

        @Override
        public String get() {
            StringBuilder buffer = new StringBuilder();
            while (in.hasNext()) {
                String line = in.nextLine();
                if (line.isBlank()) {
                    break;
                }
                buffer.append(' ').append(line);
            }
            String res = buffer.toString();
            return res.isBlank() ? null : res.trim();
        }
    }

    @Test
    public void test() {

    }
}
