package done;

import java.util.Scanner;

public class PasswordPolicy {

    public static void main(String[] args) {
        try (Scanner in = new Scanner(INPUT)) {
            int count = 0;
                while (in.hasNext()) {
                    String line = in.nextLine();
                    if (hasValidPasssword(line)) {
                        count++;
                    }
                }

                System.out.println("Result: " + count);
            }
        }

    private static boolean hasValidPasssword(String line) {
        int dash = line.indexOf('-');
        int space = line.indexOf(' ');
        int colon = line.indexOf(':');

        int low = Integer.parseInt(line.substring(0, dash));
        int high = Integer.parseInt(line.substring(dash + 1, space));
        char letter = line.charAt(space + 1);
        String password = line.substring(colon + 1).trim();
        //long count = password.chars().filter(c -> c == letter).count();
        //boolean valid = count >= low && count <= high;
        boolean c1 = password.charAt(low - 1) == letter;
        boolean c2 = password.charAt(high - 1) == letter;
        boolean valid = c1 && !c2 || !c1 && c2;
        if (!valid) System.out.println(line);
        return valid;
    }

    private static final String INPUT1 = "" +
            "1-3 a: abcde\n" +
            "1-3 b: cdefg\n" +
            "2-9 c: ccccccccc\n";

    private static final String INPUT = "" +
            "4-5 m: mmpth\n" +
            "1-7 r: rszchrrrzgr\n" +
            "2-5 w: dgqtwwkwwc\n" +
            "10-11 w: ldslpwbbqwpwtd\n" +
            "3-4 s: sszss\n" +
            "1-6 l: llmjxlbt\n" +
            "8-11 c: ccctccccccw\n" +
            "1-11 l: tllllllplllzjllgz\n" +
            "5-8 j: ljjjjjjqcw\n" +
            "11-12 s: sssssqsslsvhfs\n" +
            "7-10 f: fffffmfqfffffff\n" +
            "3-8 m: mmmsqmmmh\n" +
            "3-9 w: dwzvsttjw\n" +
            "7-8 l: llllflhg\n" +
            "10-13 f: jfkwhzrtktphc\n" +
            "5-6 p: pvldppqvcd\n" +
            "9-17 s: sssssssstssssssscsss\n" +
            "4-7 k: zlwhcwkrckwkskxkgh\n" +
            "12-14 n: nnnnnnwncnnjnn\n" +
            "6-8 g: gkwzbwhgmgrqqlksswg\n" +
            "7-8 d: drpbhdvwddd\n" +
            "6-8 d: dlmphvwbnnddrd\n" +
            "5-6 m: mmzmmmpm\n" +
            "6-13 x: xdcxhkqqxznxwhtxdxt\n" +
            "4-14 c: pncwncdcccccdmwccccc\n" +
            "14-15 s: gsrsssssbsssstkssmb\n" +
            "1-3 m: dhmzmlnfmsm\n" +
            "8-12 l: llmlrllchlwhlktpxdf\n" +
            "3-5 g: njgkglgx\n" +
            "11-14 v: vvvvmwvkvtqvgxvvvlvv\n" +
            "1-4 h: hhhq\n" +
            "1-2 l: dfrmsp\n" +
            "4-5 n: nkknnkrflkpnnn\n" +
            "10-12 w: dwwwwwwlwwww\n" +
            "13-14 h: xnhhhrvwpnkmhx\n" +
            "11-12 l: lllllklrllrx\n" +
            "12-14 d: ldrvtddrddvdqgj\n" +
            "10-11 p: bxpqplqtqzhjv\n" +
            "2-5 t: bmltz\n" +
            "8-10 j: ljjjjjjmjjj\n" +
            "5-6 x: xxxvll\n" +
            "5-7 b: bxbbbbbk\n" +
            "5-11 t: ttjmsttwtdh\n" +
            "2-3 p: dmxxrpnppd\n" +
            "1-4 x: xxxxxgx\n" +
            "3-6 v: vwcvvv\n" +
            "4-5 l: lqpll\n" +
            "14-20 p: psxqnpfpnmpsppppppsp\n" +
            "16-18 g: lgggkgggggggggggglg\n" +
            "3-5 b: tbfbbg\n" +
            "6-8 n: nsnnnnnnnw\n" +
            "2-4 p: dppndlmtnt\n" +
            "11-15 q: tqqqqqqqqqqqqqq\n" +
            "13-14 r: rrrrrrrrrrrrbx\n" +
            "3-6 s: shsssfc\n" +
            "7-9 l: mlghdlhwfbcqmv\n" +
            "1-2 k: mlwk\n" +
            "13-17 v: hbvlqvknvvsvzvvvvv\n" +
            "3-4 g: bmngrgttz\n" +
            "9-10 h: hhmhhhhhtc\n" +
            "1-15 m: nmmmmmmmmmmmmmmm\n" +
            "12-13 k: kkkkkkkkkjnfckk\n" +
            "1-8 k: skkkzkkkk\n" +
            "5-7 j: jjjjjjhj\n" +
            "12-14 g: gmgxwglgggggbggqgg\n" +
            "9-11 p: pppxppqpprlgpp\n" +
            "14-15 j: cpjjjjjjjjjjjjjj\n" +
            "4-12 l: lnblzbdmpwwrbmnr\n" +
            "3-8 d: dddhdmcrddnddnddjl\n" +
            "5-9 g: kghqfsggf\n" +
            "18-20 g: gggggggggggggggggngw\n" +
            "3-5 q: rkqlqfzvwqqqksntqdz\n" +
            "8-16 m: dkmmzgmdmmmhwmxmxm\n" +
            "7-9 q: qnqhtkqqqqqqjvcs\n" +
            "1-3 m: mmlm\n" +
            "1-10 b: bjfkmblmbbtvxzp\n" +
            "4-5 c: ccldccsq\n" +
            "4-7 k: dzbkksrkkkbkwd\n" +
            "1-7 r: rrrrrrp\n" +
            "9-10 g: qgggtgnlszgggs\n" +
            "6-7 g: ggsgjfq\n" +
            "10-11 n: nnnnnnnngnnn\n" +
            "3-4 c: ftchcgcvlgzckdrg\n" +
            "13-15 p: pppnppppppppzhpplhp\n" +
            "2-7 k: xnlhlxsdzkvhw\n" +
            "5-8 m: mmmbmqmnfmtm\n" +
            "7-8 d: sdddddcjd\n" +
            "3-4 b: fnjr\n" +
            "8-14 c: cccccrjcccccccchcfqc\n" +
            "6-11 m: mmmmmmmmmmmmmmmmmmmm\n" +
            "5-7 l: lllllwhtl\n" +
            "5-7 z: zzbzrzg\n" +
            "6-10 n: ncnznxzcwvcn\n" +
            "2-4 f: xpkffxmlwtgzjppcdf\n" +
            "19-20 c: cccccccccccccxcccclf\n" +
            "4-14 w: wwlmwwfpwwzjdww\n" +
            "11-17 f: fvfffvfffffxffffff\n" +
            "12-13 s: gtshbpzgxnsss\n" +
            "5-6 m: mmsjjgmd\n" +
            "15-17 x: xxxxxxxwxxxxxxhxx\n" +
            "5-9 f: kgfjmbctt\n" +
            "6-7 k: wkknmkk\n" +
            "2-4 c: cccc\n" +
            "5-9 s: grsgskjnsmsg\n" +
            "3-5 q: qqqqqps\n" +
            "9-11 f: fffbfbfffffjfffcffkg\n" +
            "7-9 q: qqqqknqqcmqqqq\n" +
            "17-18 x: xxxxxxxxxxxxxxxxxq\n" +
            "2-10 j: cmhglhqjdg\n" +
            "10-11 h: pnhzhkgxbhkdm\n" +
            "8-12 j: qjjjjwjjjlzjbjjdcjj\n" +
            "15-16 q: qqqqqqqqqqkckvrq\n" +
            "6-15 f: fkfffffffsfcknf\n" +
            "4-17 c: vgpsglczjdfcnqtbnl\n" +
            "10-11 k: mmxktwkkwbvfkkdkkknj\n" +
            "11-12 s: ssssssspsssk\n" +
            "3-5 l: lcqdh\n" +
            "2-3 m: mqqq\n" +
            "6-7 k: fkkkjkv\n" +
            "13-15 g: gqlgdsgggggxggg\n" +
            "7-9 r: jvnkhhrrrvrsfxkrtd\n" +
            "14-15 f: ffrffffffffqpkllfxff\n" +
            "3-4 d: gjvf\n" +
            "9-12 x: hxxxrxqwxxjxxq\n" +
            "5-7 k: wdkkkdfttqkdkng\n" +
            "6-7 x: xxxvxhx\n" +
            "6-13 c: ccsclccccfmcdb\n" +
            "5-17 c: cdccsvcccccccccck\n" +
            "14-15 s: sssssssssksssnx\n" +
            "6-7 j: jjjwhqt\n" +
            "14-15 s: kssssssssssspcss\n" +
            "3-6 w: tnmlbhw\n" +
            "1-4 g: lqgrtcgn\n" +
            "1-11 b: drrwhbwzqdj\n" +
            "7-8 r: vrnvdtrr\n" +
            "4-8 w: vwwwwwwwww\n" +
            "6-7 v: vvvvvvn\n" +
            "7-14 t: sxtxhdxcwqdgrtqs\n" +
            "2-7 w: ptgsdwghvjwmwbgrqqs\n" +
            "1-2 l: llllgll\n" +
            "3-4 n: npnnbg\n" +
            "3-5 h: mxhhhwhf\n" +
            "10-15 j: bjjjtnjppjjjzcjjsw\n" +
            "8-11 r: srkkhrrcwrbrptr\n" +
            "2-4 t: qttwv\n" +
            "8-9 t: tfhtldttt\n" +
            "5-15 r: lwdmlgrrrrtrrrpxgrp\n" +
            "8-9 d: ddcddddgwd\n" +
            "3-4 b: cbbb\n" +
            "11-12 m: vmmnxtdxmmnm\n" +
            "2-5 r: rwrvc\n" +
            "1-10 s: sssxsfsssssws\n" +
            "1-4 v: kvlxvvv\n" +
            "5-17 h: dhqhhhlxhhhhqhhbhhnc\n" +
            "7-9 d: bdddpkdnfrnmb\n" +
            "3-6 x: qvstbxvkqfnxwnk\n" +
            "16-18 m: mlmpnmmstmmlmcmbmh\n" +
            "8-9 h: hhhhhhvhhhhhhhx\n" +
            "7-10 t: tqcttwwttg\n" +
            "1-9 m: gmvlmmmqmtpfm\n" +
            "3-4 p: ppppp\n" +
            "7-17 d: xddgqhdddcptxdhxc\n" +
            "1-11 f: ffffffffffff\n" +
            "13-14 r: dmsrnztgrrlvgt\n" +
            "10-11 r: rrrrrrrrrrvr\n" +
            "4-5 l: llllll\n" +
            "4-9 k: kkkkbkkkd\n" +
            "3-5 b: vsbbbtrnqzbbd\n" +
            "2-12 j: sjgjnjmhjgcjjcnjjj\n" +
            "5-15 h: lqhvhhtxkhchmhh\n" +
            "7-14 l: sllsfllllllllllllll\n" +
            "12-14 v: pvvvvvvvvvvvvv\n" +
            "4-5 j: jjgjjjg\n" +
            "11-13 q: qqqqmqqqqqdqxq\n" +
            "7-9 p: ppppppphpnp\n" +
            "5-6 s: ssrssz\n" +
            "8-14 j: jjjjjjjjjjjjjjj\n" +
            "6-8 j: jtxjdjmjxjjjrjq\n" +
            "14-16 d: ddddddddkdddddjd\n" +
            "4-6 h: hhhhwhxh\n" +
            "5-12 h: hhphwjhjhhhhhnhhbh\n" +
            "5-9 m: mmmjxhpkmmhmttjdmk\n" +
            "5-9 c: cxcvgtccttwn\n" +
            "6-11 r: bcrrwznbgtrrrr\n" +
            "3-4 t: fpttlttxjwcqmtbw\n" +
            "2-4 b: dmxkbrgpjqtlnq\n" +
            "2-7 r: rdrfprqprkgwpxrrw\n" +
            "10-13 c: ccckpcsccwccccc\n" +
            "5-7 l: vlllllkl\n" +
            "4-11 x: xxxjxxxxvxtx\n" +
            "1-5 h: hhhhh\n" +
            "7-12 s: sjssssxnssmsj\n" +
            "4-5 w: wthmw\n" +
            "6-7 f: fkppffq\n" +
            "7-8 c: cgktccccckcccc\n" +
            "1-2 q: lhnsqrk\n" +
            "2-6 m: dvmmmm\n" +
            "3-6 x: dbxxlxkf\n" +
            "7-14 d: ddsdjslpkfddxjjjkdt\n" +
            "14-16 c: ccqcvctjcccrccgc\n" +
            "1-3 d: dddrkddddkmxr\n" +
            "7-10 w: gpwgskmxsjv\n" +
            "4-5 v: bxhgm\n" +
            "6-7 w: whwhfqw\n" +
            "1-4 x: sxxxrx\n" +
            "2-4 g: ggdggg\n" +
            "15-16 h: hhhbhhhhhhhhhhhh\n" +
            "8-9 s: ssssxsksshss\n" +
            "4-6 w: wwwlwqw\n" +
            "6-8 d: sdpqddddmddw\n" +
            "14-15 j: jjjjjjjnjjjmnjj\n" +
            "2-9 p: pvzstcclp\n" +
            "18-19 g: fgggggggglpgggggztg\n" +
            "15-17 z: zzzznzzzzfzzvztzhzzz\n" +
            "10-11 j: pjjkjkjjjgj\n" +
            "7-12 w: dwbwwbzwwwbvwmwc\n" +
            "3-11 g: vgggwqnwspgg\n" +
            "8-13 w: wwwwwwczwnwtww\n" +
            "1-11 m: mjdtsvwmcqmvd\n" +
            "2-3 c: vcccc\n" +
            "6-17 k: wskkkkkkkkgjkzkkkgmk\n" +
            "8-12 g: mghgrngjggvjgg\n" +
            "4-7 p: pppsppp\n" +
            "6-9 v: vvvvvrvvv\n" +
            "5-14 j: jjmqlzjbjjjlmjjjjj\n" +
            "1-13 f: fkbnffffffffpfff\n" +
            "3-9 r: vrfrxtvwh\n" +
            "2-4 k: fkskpjkkbh\n" +
            "15-19 d: dddddddddddddddddhdd\n" +
            "1-16 s: swtmgswssfwsxpsssss\n" +
            "12-13 s: ssssssssssslssss\n" +
            "1-2 q: wvzvbb\n" +
            "9-14 d: pddddqgcdddjddx\n" +
            "4-6 x: vbqpxxbkxmx\n" +
            "1-5 q: qzqqqqqwfmtqfq\n" +
            "7-17 l: mdlcllllhrlllhpllcl\n" +
            "9-10 q: qqqqqstcgcxqqq\n" +
            "6-11 x: txtxhxxmxhxxx\n" +
            "7-8 c: ccccccppc\n" +
            "12-13 v: vmvmvvvvvvvvxvl\n" +
            "10-12 r: rrrrrzrrglrrrrkr\n" +
            "2-4 s: ssbsv\n" +
            "15-17 g: ggggggggggggggggf\n" +
            "2-7 g: sgvgtgghmtxd\n" +
            "16-17 s: ssssssssssssssvzsss\n" +
            "4-6 n: nnnnqnn\n" +
            "10-15 t: mvtttvtftqzmtjt\n" +
            "10-11 q: qqqqbqqwqrzqqp\n" +
            "6-14 h: hjhhhchhhhjhdd\n" +
            "11-15 b: zbwhdjksbqbdbmb\n" +
            "5-12 r: mrnggrwzrhrrrr\n" +
            "9-16 m: jmmmmmmmmqwmmcxmfmm\n" +
            "7-8 h: qsmhhhtsbhhhjhwl\n" +
            "2-3 h: hkghhm\n" +
            "1-4 k: nkkkk\n" +
            "3-4 z: zzzz\n" +
            "11-13 j: jrjjgbgjxrqjrmjjgckj\n" +
            "3-7 w: wwwqqlwdb\n" +
            "6-9 b: fsbbbqbbqmbb\n" +
            "13-16 n: nnnnnnnnnnnnnnnn\n" +
            "5-7 b: cbbqmbbrhbbz\n" +
            "2-3 l: xjzkbwgfwwcwll\n" +
            "13-14 z: zzzzzzzzzzzzzzzz\n" +
            "6-7 c: ccccccc\n" +
            "4-10 l: lhlslmlwmwbllv\n" +
            "4-5 h: rqhhhhh\n" +
            "3-4 t: dmtttmxhtqz\n" +
            "6-17 n: nnxcnncnnvgcnnrnrmn\n" +
            "3-4 x: xxmxxx\n" +
            "8-10 j: jjjjjjtjtvjj\n" +
            "5-11 d: ldldbnndddddsgdpgj\n" +
            "1-8 n: nsjvhncn\n" +
            "3-8 f: fffffssffxfffhl\n" +
            "1-3 q: kwnq\n" +
            "3-5 k: krkcklkhkspqmqm\n" +
            "3-4 k: dklm\n" +
            "11-14 j: jjjjjjjjjjjjjjj\n" +
            "16-17 v: vvvvvvfvvvvvvvvmx\n" +
            "5-6 m: mmmmmm\n" +
            "10-11 l: wdlgllqlslf\n" +
            "5-6 t: prbwttmtpvwr\n" +
            "6-20 c: cwcctqccthccrpccccct\n" +
            "5-12 s: sssssbssssszs\n" +
            "10-11 k: mkkjklhkktkkkdvkqqkm\n" +
            "11-12 n: nnnnrnnsngnn\n" +
            "2-5 p: ppppl\n" +
            "7-11 f: mvmdfmdwfffffwfrjfqk\n" +
            "13-16 r: rzsrdsrrrrrrprpjrb\n" +
            "13-14 c: ccccccdccccctc\n" +
            "13-18 n: nnnnnnnnnnnncnnnnnn\n" +
            "4-10 r: rvrrdhflcrtwzz\n" +
            "2-9 p: prpczpbpt\n" +
            "3-8 q: qqqqcksqqtx\n" +
            "4-5 d: xxdpmdbvddn\n" +
            "3-4 j: jjlj\n" +
            "2-3 n: nrnnnsnn\n" +
            "3-4 w: pnwkwdn\n" +
            "1-5 w: wlwgw\n" +
            "10-14 x: xxxxxxxxxxxxxxx\n" +
            "5-15 k: kkkkfskkhkkkqpf\n" +
            "3-4 b: bbbbf\n" +
            "3-4 r: jrrr\n" +
            "3-6 h: htkhhhhh\n" +
            "15-16 g: gggggggggggggvgt\n" +
            "17-18 s: ssssssssssgssssssz\n" +
            "14-15 m: pkngmmpjmxmmmms\n" +
            "4-10 f: rsmxvsghdlfff\n" +
            "16-17 z: zvzhzzczdvzkzzghg\n" +
            "16-18 v: vvvvvvvvvvvvvjvvvv\n" +
            "6-9 t: tttttmttttt\n" +
            "5-6 j: hjwxgbjf\n" +
            "3-6 k: kkkkkh\n" +
            "9-13 d: ddpgdfddddddd\n" +
            "14-15 x: xxxxxxxxxxxxxxx\n" +
            "1-4 v: vqvqkrjx\n" +
            "4-5 h: hjhhnh\n" +
            "2-3 v: jvvsrgsvfqlv\n" +
            "9-10 m: mmmmmmmmmm\n" +
            "2-5 f: ffnfpff\n" +
            "4-6 b: bbbbbg\n" +
            "8-9 p: ppjwqpjbnpppwp\n" +
            "5-6 l: lldlllll\n" +
            "9-10 g: gvgqggtgggggg\n" +
            "6-9 x: jxxxxxwxqqvxx\n" +
            "1-4 w: lwwgbt\n" +
            "16-17 d: jcdmgkmfvvlqphbddvhc\n" +
            "1-12 s: sssslssssssnsss\n" +
            "4-5 p: cjnppjllxbrp\n" +
            "13-14 n: jmzjhttnkkgnnn\n" +
            "11-12 t: vrgtrgjrdmtcfzx\n" +
            "16-17 l: lllllnmlvldlllrwmlc\n" +
            "13-16 m: mbdmmmmmmhmsmmmmtb\n" +
            "3-6 z: zszzzzz\n" +
            "1-6 h: hhhqhrbh\n" +
            "3-5 n: rlnnnn\n" +
            "17-19 x: xxxcxxxvxxxxxxxxxxkx\n" +
            "3-10 r: rccrrrhrrx\n" +
            "4-7 h: hhhdhhh\n" +
            "3-6 g: hgfzpmpgg\n" +
            "1-2 x: xxqhhx\n" +
            "5-6 m: jmmmmzf\n" +
            "1-2 j: bjjj\n" +
            "2-3 q: gqst\n" +
            "3-4 g: ggggmbghk\n" +
            "3-4 f: fnfdf\n" +
            "5-6 q: qpqtdg\n" +
            "2-3 t: ptctz\n" +
            "5-6 d: pddvdddsd\n" +
            "1-4 f: ffftff\n" +
            "3-5 b: bbdbg\n" +
            "13-17 f: fgfckcdfffftffxfffff\n" +
            "3-4 w: wwkxsw\n" +
            "2-12 l: hvgqmbqlrnzls\n" +
            "1-2 f: szff\n" +
            "6-7 q: sqqqqnqq\n" +
            "1-4 p: ppvd\n" +
            "3-7 c: cwscbkgc\n" +
            "4-12 s: sssfsssspsfsgss\n" +
            "4-10 t: jstttgststtghzp\n" +
            "5-6 j: jjjjtj\n" +
            "5-9 k: ffkdktkkhbbwkkj\n" +
            "9-15 k: kkkkkzkkkcbkkkkkkkkk\n" +
            "3-17 w: wwgwnnkswwpqwkwdhw\n" +
            "15-20 l: wlllllslllllrllllllk\n" +
            "4-5 r: rrrfm\n" +
            "2-6 l: flllnll\n" +
            "12-13 s: ssssssssssscwn\n" +
            "9-10 r: zpqrrrrrfn\n" +
            "10-13 h: xhhfhzchhjhhtdrhhzh\n" +
            "6-7 b: bbbbnrbb\n" +
            "2-12 f: tffjcjtlnvgf\n" +
            "2-4 g: gtgkg\n" +
            "11-14 n: nnnnnnbrnnnpnnn\n" +
            "15-17 j: jjjjjjjjjjjdjjvjv\n" +
            "10-13 r: brgrrrfrmfrrxrgrrrs\n" +
            "3-13 v: vwvjsftzkvcxvdbxfs\n" +
            "17-19 f: fffffffffmffffffffff\n" +
            "1-4 g: vggxg\n" +
            "5-16 m: csckdfxglfpzmrhcmbnn\n" +
            "4-15 z: gzqjzczzzzjzzhjbz\n" +
            "13-14 w: wwwlwwwwwwwwht\n" +
            "11-13 j: cjjdjjjjsjjjkjjjh\n" +
            "4-15 w: wwwqwwzwwmwwtww\n" +
            "1-2 p: ppjcp\n" +
            "6-10 f: ffjffrfffsgm\n" +
            "17-19 q: qqqqqqqqqqqqqqqqqqqq\n" +
            "3-4 g: gmgz\n" +
            "10-14 s: fpsssdmssdsgsgvss\n" +
            "9-10 m: mmmmmmmmmmmm\n" +
            "1-5 c: fcgns\n" +
            "5-9 t: ttcgtttrtttttq\n" +
            "4-5 v: vvrvvv\n" +
            "2-4 w: xwpw\n" +
            "5-12 d: trdhrqlqwrlsrdfh\n" +
            "3-8 n: bbnnnzrnnjdnb\n" +
            "8-10 w: wwwrwdwjgz\n" +
            "5-6 d: ddddjr\n" +
            "1-3 p: ppqppp\n" +
            "10-19 f: dfbjgffmpvnkhfwjfff\n" +
            "3-6 k: kkkkkkkp\n" +
            "5-7 t: vqtxtxtvk\n" +
            "14-15 c: cccclccccccctcctwc\n" +
            "2-13 x: tmxxzxklxgzxxp\n" +
            "16-17 b: bbbrbbbbbbbbbbbbbb\n" +
            "6-11 h: gmzhhhhmrhqhhm\n" +
            "7-9 k: kkkkkkqkck\n" +
            "4-7 v: pgvdvvx\n" +
            "12-19 f: fffffffffffxffffffff\n" +
            "2-5 p: mphtpp\n" +
            "6-13 t: ctttvwtntqttttq\n" +
            "3-11 t: xntrzxtlnwt\n" +
            "17-18 l: llllllllllllllllll\n" +
            "2-5 c: zczpcfdzblnkcvj\n" +
            "1-5 z: fzzzmz\n" +
            "6-11 f: tdcffpffwqlfffg\n" +
            "16-17 h: hhhhchhhhshhhhhdhh\n" +
            "13-14 m: msmmmkmmmjmmmmzmmnm\n" +
            "6-13 s: nhbscsgcssxsrsssx\n" +
            "5-17 q: qqvqqqhqrkqqqqgqqq\n" +
            "2-4 t: vqtbt\n" +
            "2-5 t: wfdrsrt\n" +
            "6-7 f: ffffzdx\n" +
            "3-13 r: pmrtkvdcrxrnrzw\n" +
            "14-18 r: wrrqrrcrrlrjmrrkrt\n" +
            "15-17 j: jjjjjjjcjjjjjjxjt\n" +
            "8-9 h: zmhhlmhhhdhhhhg\n" +
            "6-15 l: lllllnlfllllllll\n" +
            "3-5 n: nnfnb\n" +
            "16-17 s: sssssssslssssssss\n" +
            "8-9 k: kdkjkkkskkk\n" +
            "2-5 z: gzzmzhdplnwwvlsjnzv\n" +
            "4-15 r: rvmrbsrtrfdqrrb\n" +
            "6-7 l: llllllc\n" +
            "4-7 g: dnggxhgggg\n" +
            "8-9 f: fftffkdff\n" +
            "6-9 r: rrrvrprbrz\n" +
            "2-6 q: qwqqqqq\n" +
            "7-9 h: mzhpwnkhh\n" +
            "3-4 m: mmlh\n" +
            "1-15 v: vjpkvdzvzdlklpn\n" +
            "1-3 r: rrggvr\n" +
            "8-13 d: dwrpdsdjhlddqddhdwdp\n" +
            "3-4 r: fvrrsprrmrrrjgr\n" +
            "4-5 s: zsrssvss\n" +
            "6-7 d: dfdwtcvgvcdfdqdwd\n" +
            "6-12 n: rhnjnndnfnwql\n" +
            "3-5 l: hvlxlcnclqllrw\n" +
            "10-14 l: llllllllljlllplll\n" +
            "6-10 b: bbbbbbbbbbbbbbbbb\n" +
            "8-11 q: qqqqqqqtqqqq\n" +
            "7-8 r: rrrrrrxf\n" +
            "1-4 k: jkkkzsmbtng\n" +
            "13-17 r: rrrrrrlrprrdrrrrl\n" +
            "1-7 t: dfgnvtl\n" +
            "2-6 v: qvvdsm\n" +
            "8-9 l: lltlrlljb\n" +
            "3-4 m: mdmm\n" +
            "17-18 t: ttttttttttttjtxttwtt\n" +
            "9-11 b: bbbbbbbbbbpb\n" +
            "2-3 b: bwnbr\n" +
            "4-10 t: tfdtltstdft\n" +
            "8-10 z: zzfzzzztzzz\n" +
            "6-8 q: qqqqqqqmqnqqq\n" +
            "7-11 r: rzrrrrzrrrr\n" +
            "11-13 k: kkkklklbkmklk\n" +
            "17-18 l: slllllblllllllllclll\n" +
            "10-14 s: ssssssssswssssssss\n" +
            "3-4 s: hwssssgjsp\n" +
            "7-10 g: fbggxgtbngg\n" +
            "6-7 z: tzzzhzjz\n" +
            "3-7 g: ggggggcrg\n" +
            "16-20 g: grgghjcnlmkszxrgtgvv\n" +
            "1-16 n: prqnwnngbgtjsvsj\n" +
            "13-14 z: zszlgqdgtqbzzlpkzz\n" +
            "4-8 f: ffftffnnfp\n" +
            "15-18 s: jrdgssszdxkzhlsfzs\n" +
            "7-8 l: llllllbplllllll\n" +
            "7-10 l: llllbllllll\n" +
            "5-9 b: bbbbwbbblb\n" +
            "4-5 g: gdwhdg\n" +
            "2-3 v: jnfvvv\n" +
            "11-13 h: hhhhhxhhhmzhbj\n" +
            "11-13 r: wbrrrrxgwlvwd\n" +
            "10-12 m: gxmpmmmgmmmmm\n" +
            "11-12 h: hhhhzhhhhjhnhhh\n" +
            "2-13 g: kzkztgnlbqhlgx\n" +
            "4-7 z: zktzzzzx\n" +
            "1-7 q: pqrxqqhfpglwqts\n" +
            "6-7 f: pffvfbtf\n" +
            "6-7 l: tlljjlllnll\n" +
            "4-17 f: flffpffffdfqffscff\n" +
            "2-4 q: bqxqrqrrq\n" +
            "6-8 l: lllnllfll\n" +
            "9-12 r: xrgrrjrrrkgrrqrnr\n" +
            "14-19 r: rrrrrrrrrrrrrrrrrrrr\n" +
            "18-19 w: lbqrkdwwwqgrklcwxwwh\n" +
            "9-10 n: nnnnnnnnnn\n" +
            "7-13 b: bbbbbbbbbbbbb\n" +
            "5-7 k: hkbfskqkjktwkk\n" +
            "9-10 c: tlvmtfcpccwwz\n" +
            "3-7 r: rzzrspmp\n" +
            "7-11 g: gghzgglgggt\n" +
            "4-5 p: pbpwp\n" +
            "3-6 q: qqrqqv\n" +
            "3-13 m: mmmwxmmlmnvmmmmmm\n" +
            "2-6 p: ppplqpfpp\n" +
            "11-15 t: ttttttctttltctgt\n" +
            "2-7 m: cmnhjqm\n" +
            "1-6 m: mzjmtmmmmmdw\n" +
            "1-10 j: jzgjcjjjjspjjjjjgjmj\n" +
            "4-7 r: vmxtrrnrxnnq\n" +
            "8-16 h: hhhhhqhfhhhhhhhhhh\n" +
            "4-10 z: kcmkzmzpzts\n" +
            "14-15 j: jjjjjjjjjzjjjjj\n" +
            "6-11 x: xxkmxxcxxvx\n" +
            "15-16 v: vvvvvvvvvvvvvvgt\n" +
            "6-7 w: wwwwwgqz\n" +
            "5-7 d: dkdpmcddjdd\n" +
            "6-12 s: sssssssssssvs\n" +
            "8-10 q: fcpwtgqqqz\n" +
            "4-5 w: wwwwgwww\n" +
            "8-11 q: qqqqqqqnqqbqqr\n" +
            "3-4 d: dddwddd\n" +
            "9-12 x: qxcgxxxxvdxdkzxxxxx\n" +
            "3-8 k: kqcsjxszvscfvm\n" +
            "4-7 d: mgdddddhkdqb\n" +
            "3-7 x: xjxxljlsfrfnhsxxlv\n" +
            "4-9 g: xgsxgtgggxmgg\n" +
            "1-4 p: tppknptkp\n" +
            "3-7 z: gzzbzzz\n" +
            "1-5 p: ppgpz\n" +
            "15-16 f: fzfffffffffffffwff\n" +
            "5-11 t: tzttvqltfxtg\n" +
            "6-7 v: vhqvzpvv\n" +
            "2-6 f: fmffftfff\n" +
            "9-13 d: dxrdgddddrddddqpgdd\n" +
            "7-8 r: rrrrrnlnrr\n" +
            "5-6 t: btttwm\n" +
            "13-14 g: gggggggggghgblgg\n" +
            "12-19 r: qkgrvfnsrwzrqsrhrrs\n" +
            "15-17 j: jjjjjjjjjjnjjjhjd\n" +
            "4-9 t: btmrbcgttjht\n" +
            "16-17 n: nnnnnnnnvnnnnnnznn\n" +
            "3-7 l: lltlllglll\n" +
            "12-14 v: vvvvvvvvvvvvvv\n" +
            "1-3 q: qqqq\n" +
            "12-14 f: flbfphvwfdffjf\n" +
            "10-11 z: lszzzzzzzzzzz\n" +
            "3-9 k: lvzkkhkkp\n" +
            "4-6 j: fmrjccsjrzjqkfvn\n" +
            "5-11 x: xxxxvmxxxxcxx\n" +
            "1-9 c: wcccccccjxcvccccc\n" +
            "1-4 l: sblllll\n" +
            "1-2 x: xnvlnxs\n" +
            "4-5 f: nffccfff\n" +
            "8-9 p: vpppppprz\n" +
            "1-6 d: vfcqmddw\n" +
            "6-7 b: bbbbbbb\n" +
            "7-13 n: nnnnnnnnnnnnwg\n" +
            "3-6 q: zqqqqqqqqqpqqqq\n" +
            "1-9 g: gbggggdgglgmg\n" +
            "9-13 b: wbbbxnbbqbbbbkbb\n" +
            "4-5 g: gggwr\n" +
            "3-9 r: vnqvvhprzmbhrcb\n" +
            "10-11 m: mmmmmmmmmpm\n" +
            "4-7 c: cgrbccdbcz\n" +
            "5-8 r: rbvrrrrr\n" +
            "7-11 d: ddddjdmddfhvdn\n" +
            "1-2 k: zjkk\n" +
            "2-11 w: wtwwwwwwwwsw\n" +
            "7-8 b: bkbbbbfbbxd\n" +
            "2-4 w: wwnjswwmgbwrwwm\n" +
            "9-18 j: jjjjjjjjkjjjjjjjjs\n" +
            "6-7 t: tttttvwtttt\n" +
            "10-11 v: wvvvbvvvvvvvm\n" +
            "17-20 d: ddddddddddddhddddddn\n" +
            "2-12 q: qdqqqqqqqqqxqqqqqq\n" +
            "5-7 w: rjdswwwwwwqmmpww\n" +
            "1-9 b: bbbbbbbbxcbbbb\n" +
            "4-5 q: qqqwxp\n" +
            "10-15 n: nnmnnnnnncnnnnvn\n" +
            "10-17 f: fnfffffffffffffcff\n" +
            "2-3 p: krpx\n" +
            "8-10 c: cvsccclwccrcjjclc\n" +
            "5-9 t: fpnhtmtqtvwcss\n" +
            "10-13 r: rrxrrrrrrfrrrr\n" +
            "6-9 l: lllllwllt\n" +
            "11-15 n: dnnnnnnhsxgnnhsn\n" +
            "14-16 b: bbbbbbcbbbnbwkbsbm\n" +
            "3-8 g: qhlxgggqvg\n" +
            "11-14 x: ptqcgxnnhpxbgxlm\n" +
            "17-19 g: gggggggcgggbggggngg\n" +
            "10-19 q: qtjrqqwjvqqqknqbqqq\n" +
            "10-13 j: jjjjjjnjjljjsj\n" +
            "1-3 g: mggg\n" +
            "3-7 w: pwtwjdq\n" +
            "1-2 j: jjjp\n" +
            "9-13 z: pszzzglzhzzzzhz\n" +
            "1-2 j: fhhjxz\n" +
            "9-12 l: llllllllsltll\n" +
            "7-9 c: cxdvzcclccz\n" +
            "13-15 g: ggggggggfggggkgg\n" +
            "15-16 z: zjjbgzlxqzzsxzdxz\n" +
            "2-3 z: kxcszzzsrsccg\n" +
            "7-9 t: sttwxgtwlbzbsffttjb\n" +
            "1-6 r: rnmrrrtrrl\n" +
            "4-7 m: pmmtmmq\n" +
            "5-7 f: lggcpdpf\n" +
            "16-19 j: jxjjxjfssrvlmjjfjjmq\n" +
            "2-8 w: wrwswcwvw\n" +
            "4-15 k: kkkpkkkkkkkkkkq\n" +
            "12-15 s: xbssnshpsssgsbk\n" +
            "7-15 z: vzrzzczbhzzzzzzzhz\n" +
            "10-14 w: wwwwwwwwwtwwwwwwp\n" +
            "11-12 k: kkkkkkkkkkkkkckkkkq\n" +
            "15-16 s: sfssvsssssssmspl\n" +
            "4-5 d: dddqd\n" +
            "5-7 h: phsblhnfhchb\n" +
            "8-11 x: rxxxbhxxxjxxxtgsc\n" +
            "11-13 x: xxxxxxqxxxnxvx\n" +
            "5-10 p: jbpzfmphpwpz\n" +
            "9-13 v: vvvvshvvgvsfqvvvv\n" +
            "4-7 r: rrzwrzdr\n" +
            "11-13 f: fffffxffffzfwf\n" +
            "13-14 s: ssssssssssssss\n" +
            "2-11 c: czccdmkhhcvcc\n" +
            "7-11 w: wwsxwwwwwwwwj\n" +
            "7-9 t: ttknmtxvttttnt\n" +
            "1-6 r: rrpjrrrr\n" +
            "5-9 v: vkvvjqvvbvtlv\n" +
            "1-5 q: mwvhpqqqcj\n" +
            "1-5 f: fffff\n" +
            "4-5 r: trrcv\n" +
            "10-12 s: sssssssssssvss\n" +
            "4-5 d: drddzd\n" +
            "4-5 n: nnknl\n" +
            "10-12 x: xxxxfxxrzbxzvtxlxt\n" +
            "4-10 v: sbgsvssbnhmh\n" +
            "3-11 n: dnngqwnnjtnjjg\n" +
            "1-2 w: xdsvzdmzswwwwwwmgjw\n" +
            "6-8 h: whhhhmhbhh\n" +
            "2-18 w: wswwwwwwwwwwwwwwwwww\n" +
            "11-12 v: vvvvvvvvvvvv\n" +
            "7-10 v: vrhvvcvvvvvv\n" +
            "4-9 r: rrrrmzntrsgrrkhhr\n" +
            "4-5 v: vvvtvc\n" +
            "3-10 t: ttnttwzgptr\n" +
            "2-3 c: gccrngp\n" +
            "2-3 b: bbbqx\n" +
            "1-7 s: zsdlsjs\n" +
            "5-7 j: jjjjjjj\n" +
            "2-5 g: ggnhg\n" +
            "2-6 w: fwwkwhjqbwqw\n" +
            "1-6 w: wdgnjwqwqv\n" +
            "9-11 b: bbtksbbdxbpjbbbbb\n" +
            "12-15 k: kkkkkkkkkkkkkkk\n" +
            "1-6 b: bbbrbbb\n" +
            "6-7 g: gggggvs\n" +
            "8-14 s: sssnwssrsssslcs\n" +
            "1-6 q: ngjprqqmdwgkjqvq\n" +
            "11-12 z: vzzkzzgzzzzzzz\n" +
            "3-4 n: nnnnnnnn\n" +
            "5-6 b: fbwbljf\n" +
            "11-18 h: hhhhhhhhhhshhhhhhlh\n" +
            "2-15 r: rrzgrzwrblrfwfrsd\n" +
            "6-11 n: zncnknknbgn\n" +
            "13-14 f: vwffftfffpffzfff\n" +
            "5-6 c: fcccbc\n" +
            "5-6 b: bxjbcpsbrgbgn\n" +
            "2-7 f: tffhrsf\n" +
            "7-12 g: ggggggtgggggg\n" +
            "4-5 t: ktphttltctt\n" +
            "4-6 w: fwsgwh\n" +
            "7-8 m: mfmmmmmmm\n" +
            "4-5 z: gzjzzfjzzz\n" +
            "8-9 l: lvtllllllll\n" +
            "3-5 m: rsmmd\n" +
            "10-11 r: rrrrrrrrrlz\n" +
            "11-13 j: hhqtkwznghbfsbwpvrj\n" +
            "4-5 z: zjzndzrmqzlptg\n" +
            "13-16 m: mmhmmmmmmmmmpmrmmm\n" +
            "5-7 p: pppphpp\n" +
            "2-3 s: zscgsj\n" +
            "14-15 h: hhhhhhhhhhhhhlhh\n" +
            "2-3 f: rffrtlxwfff\n" +
            "1-3 z: ptqlzzxskrjsnp\n" +
            "3-4 t: ftttst\n" +
            "8-9 t: thtttttpttm\n" +
            "11-13 g: qzhmgptdfwggqqc\n" +
            "6-9 f: nfffhfkffhf\n" +
            "2-3 w: qsxgww\n" +
            "11-12 d: ddddddddddddd\n" +
            "2-4 v: qsbvvv\n" +
            "8-13 z: zxczszkwxzgkz\n" +
            "2-4 t: cbtt\n" +
            "2-5 q: clndcnv\n" +
            "8-12 f: kfnhqbfnnpntfsvxcx\n" +
            "2-3 d: gddtd\n" +
            "1-9 z: tztzzzdnm\n" +
            "3-7 h: hhhhhhhhh\n" +
            "5-6 t: tttttvtttt\n" +
            "5-9 g: npzggdhvggpqgxwgvgsg\n" +
            "3-12 p: kwpptpplxrcgfxphpqbg\n" +
            "15-18 f: fffjffffffffffwffff\n" +
            "7-17 n: nnnnnnnnnnnnnnnnnnnn\n" +
            "5-10 d: dndddkddddx\n" +
            "1-7 v: cvhvsvhvv\n" +
            "5-7 f: fscrtxlz\n" +
            "1-14 b: bbbbbbbbbbbbbbb\n" +
            "1-11 n: nnlnxntnlxnnnktnnxb\n" +
            "13-18 p: pppzppppfqhppppzrp\n" +
            "7-8 h: hhhhzhhmqhh\n" +
            "16-17 r: rrrrwrrrrrrrrxrrrr\n" +
            "4-8 f: wfffgnff\n" +
            "15-16 j: jswvgtfhtffjgjjsxsdq\n" +
            "16-17 n: nnnsnnnnnnnnnnnnnnn\n" +
            "7-8 w: dxhcjvwwzwdddhhwwlj\n" +
            "1-13 h: ppshfshghphcq\n" +
            "5-15 b: cbxnbhbbjbhbbmbkvz\n" +
            "2-11 c: tdgcqlcccccthwmk\n" +
            "1-4 p: mpppp\n" +
            "1-4 x: xpzxxkzlrsgrbxpklcz\n" +
            "2-11 f: qffffgfffcgn\n" +
            "14-19 h: hhhhhhhhhhhhhsbkhhqh\n" +
            "9-12 h: hclhhhpsvhhfhh\n" +
            "2-6 s: lqcppxlsfv\n" +
            "6-9 v: vvvvvnvvv\n" +
            "9-10 q: xqqqqqqqqqq\n" +
            "3-8 m: qmmcjmvmckrmm\n" +
            "4-9 h: hhhdhfhhs\n" +
            "1-14 r: vpsprlstjkrmmrpzqsz\n" +
            "6-7 g: ggggrlqg\n" +
            "7-10 t: dtkttptttttt\n" +
            "3-4 n: vkkf\n" +
            "9-11 g: gflgwgggrgmmggg\n" +
            "3-19 l: blblmlrlllhbllwllll\n" +
            "12-13 x: gvxsxkrvdqbxx\n" +
            "11-12 b: bbbbdpdbbwls\n" +
            "2-13 n: nnnnnnnnsnnnrnnnnn\n" +
            "6-13 n: mfnnnnnkxnnnn\n" +
            "5-6 f: kxxfqnf\n" +
            "4-5 x: xxxxl\n" +
            "6-13 f: nsnxwrftkcgzffv\n" +
            "6-7 w: wwpwwxl\n" +
            "5-7 m: brvmmnw\n" +
            "1-4 r: rkbhnmdt\n" +
            "9-10 b: knbzbbfnfbbblrqbrbnj\n" +
            "2-5 v: vvvxvvxbw\n" +
            "3-5 q: qcsjq\n" +
            "7-15 c: gcdpccrcddccwccf\n" +
            "13-14 h: hhhhhhhhhhhhhh\n" +
            "10-11 l: rllllllllllpcs\n" +
            "10-11 w: wwwwwwwwwfw\n" +
            "2-7 f: fxtfffn\n" +
            "3-5 x: xxxkx\n" +
            "3-6 c: ccrrwbsj\n" +
            "1-4 g: gggggpgqgg\n" +
            "1-2 t: vztj\n" +
            "4-11 c: zccccccccqcc\n" +
            "5-11 p: hbpzppdlppp\n" +
            "3-5 h: frhhhzhprz\n" +
            "4-7 d: mzdnddd\n" +
            "15-16 t: gttttttttqttntttc\n" +
            "1-8 c: ccqcjbhpccczvfck\n" +
            "2-3 b: lztcb\n" +
            "4-5 d: ddddd\n" +
            "2-8 j: pwfjfdjjjjzkjcjrlwr\n" +
            "10-11 m: qmmmmmjnmpmmmmxn\n" +
            "10-17 f: ppbfdsjvpfhzccbwfr\n" +
            "4-8 c: cfnhqtcmcws\n" +
            "4-6 b: bbqxpfzqfvkpbhcbdfn\n" +
            "4-5 k: kkkkx\n" +
            "4-8 f: vpwfkfff\n" +
            "1-3 t: ttxtvtthttg\n" +
            "3-4 j: fjjj\n" +
            "18-19 v: vvvvvvvvvvvvvgvvvxp\n" +
            "11-14 q: qqqqqqqqqqqqqq\n" +
            "2-3 p: ppplxprwvjmf\n" +
            "7-14 q: qpqxzqqqqqqgqmgqqgq\n" +
            "3-7 x: dqlxtkx\n" +
            "6-7 f: sfczgfffzfhffjkkf\n" +
            "1-4 x: xxxxfwxxxpmxd\n" +
            "4-5 b: jbbbbb\n" +
            "10-11 p: vrpvpppppppdppp\n" +
            "18-19 l: llllllllllllllllllll\n" +
            "4-10 v: jjzvnsfbbvqcdfq\n" +
            "16-18 d: ddddddddddddddddddd\n" +
            "13-14 t: ftttdtkrdtktttlttkd\n" +
            "3-17 d: ddkddfldddddddddr\n" +
            "10-20 v: hfzhttvvnkxqvvhlvvvq\n" +
            "5-6 t: tbwtszgwpntthtvttrsj\n" +
            "5-6 s: ssshsstds\n" +
            "2-4 h: hhhb\n" +
            "6-7 b: bbsbfbb\n" +
            "2-12 n: znvqnslfhnwnqr\n" +
            "16-17 g: gggkggggggggggggl\n" +
            "4-12 j: vjqdjjjtsjdjv\n" +
            "14-16 j: jjjdjljjjjjjjjjjjp\n" +
            "4-14 d: dddddtqdddddddd\n" +
            "3-4 m: mpmm\n" +
            "7-8 c: ccccccdc\n" +
            "3-8 l: clllhnlllrzzgll\n" +
            "9-10 c: ccccccccbx\n" +
            "3-4 k: kkkj\n" +
            "5-12 r: rrrtjxhxzbrrf\n" +
            "4-6 w: wwwkwhww\n" +
            "7-9 m: fqrmrmmmmgmmmtmb\n" +
            "3-11 w: kwwnwwwghhgw\n" +
            "9-11 k: kkkkkkpkkkktvkkk\n" +
            "5-9 w: hwqjflkkwdqmwmcw\n" +
            "12-16 h: hmhmhhhkxhghhhhhhhhh\n" +
            "1-4 z: zjzlhjpft\n" +
            "1-6 d: dddqdd\n" +
            "1-9 s: ssssssssss\n" +
            "2-4 d: wddf\n" +
            "7-9 k: nhzkkmkxkhkphkdkkd\n" +
            "12-15 m: khmmmmmmhgmmmmmmm\n" +
            "3-9 n: jnknnnnnn\n" +
            "6-8 g: ntgggfggmlrgcggf\n" +
            "12-15 g: gggghggggmgmggdgg\n" +
            "7-13 x: rxxxxxrxxxxxnqxwsxx\n" +
            "3-5 n: bnnbnnvdwnls\n" +
            "3-5 v: mvbnzk\n" +
            "2-8 n: npntnnnjnxknb\n" +
            "6-11 t: ttftttlqtttt\n" +
            "5-7 g: ggggmgp\n" +
            "5-7 x: xxbjcxw\n" +
            "1-8 d: ddddldddddddwdddd\n" +
            "2-4 s: csswjbfnjnm\n" +
            "3-4 m: mmmr\n" +
            "16-17 z: zzsspzjzzzzzznzzz\n" +
            "3-4 r: rvzpfr\n" +
            "3-5 p: wpgxpb\n" +
            "4-5 r: qlrrr\n" +
            "7-9 q: vqzzqqrqtf\n" +
            "6-14 c: qcfwcfcchcvzzgcl\n" +
            "2-11 r: brhlrbvrlrrr\n" +
            "7-13 l: lllllllllrlllll\n" +
            "2-7 w: twfwwdwvzwbw\n" +
            "4-5 z: zzzbzz\n" +
            "3-4 q: qzzt\n" +
            "3-11 h: hhhhhhhhhhhh\n" +
            "5-12 c: cdclccgcccxfczrlcc\n" +
            "5-11 p: lmgprpppvphpj\n" +
            "2-5 r: rgkqrdsrxlmddmkktpnr\n" +
            "1-4 m: zmgfmqmmmxfm\n" +
            "15-16 f: ffbffffffffffwvnf\n" +
            "19-20 l: ltllllllllllllllllhl\n" +
            "2-6 j: spthjkftw\n" +
            "3-10 r: rrrrrrfrrmrrrr\n" +
            "1-8 n: nndfhqxn\n" +
            "6-7 j: zjjjjjj\n" +
            "12-14 k: qvgcvhmzkkrcck\n" +
            "6-8 k: kkhbkhkkkk\n" +
            "10-12 s: ssrssxssslsj\n" +
            "9-18 h: dsmxxwndhgjpztkqhh\n" +
            "5-6 m: mmmmlf\n" +
            "4-5 x: xxxlh\n" +
            "9-15 b: bbbcsgbdcbbrbrfbbbbb\n" +
            "6-15 j: nfbjrpjjqjjxsbjt\n" +
            "1-6 c: cncpkcfwcd\n" +
            "2-4 m: xmmhmjbcmdmm\n" +
            "4-11 s: lhdssvkldhsqssdjgs\n" +
            "14-19 t: ttttttdtttttlttttttt\n" +
            "2-4 x: gxxxbxk\n" +
            "2-6 k: kkpqkkkz\n" +
            "10-11 w: wwwqwwwwcgqwww\n" +
            "8-9 s: sssssssss\n" +
            "2-4 v: vvvwsrb\n" +
            "12-16 s: rtcsfwssdswthfpf\n" +
            "3-11 g: fgnggtlgbgd\n" +
            "2-5 c: ggccc\n" +
            "10-15 h: hhhhhhlhpghhshh\n" +
            "1-5 n: nlhqnj\n" +
            "7-10 f: fnfffffhffff\n" +
            "5-6 t: tfttkvt\n" +
            "1-4 c: mgcsrv\n" +
            "10-17 g: bggpmggggpgggggwqh\n" +
            "3-7 p: pprvppp\n" +
            "5-8 n: xnnqndnznf\n" +
            "6-11 b: bbbbrbfbrcdb\n" +
            "3-10 k: pcfknlqkgkpzkknk\n" +
            "10-11 m: mmmmmmmmmmc\n" +
            "3-4 v: fwvvh\n" +
            "2-7 l: zlcvxwrhlnnlkhr\n" +
            "1-7 q: vqqqjqsqqqqvrqqq\n" +
            "6-8 d: ddddddddd\n" +
            "1-3 z: zkzlrz\n" +
            "5-11 w: wbfzwdwpwdfztsrxzcw\n" +
            "7-9 s: qsssclssl\n" +
            "3-5 l: cvmlgk\n" +
            "9-12 s: qsrssnsvsxshqsdtd\n" +
            "8-12 m: wmxsnmmmfwzmf\n" +
            "1-12 x: xxxxxdxxjxxdxxxxxx\n" +
            "4-10 r: rwrlbkkmqrxr\n" +
            "5-13 g: ggggggggghgggx\n" +
            "11-15 w: wwwwtwnwwwvwwft\n" +
            "9-10 q: qqqqqqqqwfq\n" +
            "6-13 q: qmhfqqxkmcjwqmc\n" +
            "2-8 r: rrrrcmrrrrq\n" +
            "12-14 m: mmmwmmmmmgmhmt\n" +
            "2-6 t: ttvtctt\n" +
            "3-6 r: qcrrpsxjttqrrr\n" +
            "7-8 g: gggggggk\n" +
            "13-15 w: wwwwwwwwwwwwwww\n" +
            "8-12 p: qqphwpjmwppfpvwrp\n" +
            "7-10 c: cccccwtccc\n" +
            "8-11 w: kwtwrwwwwcqwww\n" +
            "9-19 z: zzzzzzzzzzzzzzzzzzz\n" +
            "4-5 q: qqqsq\n" +
            "6-9 c: cxfcccgcccpc\n" +
            "7-9 d: nddlddxdgddzd\n" +
            "3-12 q: qrghqxqjqqdwqqq\n" +
            "14-15 w: wwwwwwwwwwwwwqmwwww\n" +
            "14-15 c: frcwcctccrccccc\n" +
            "2-5 v: vqvvdvv\n" +
            "3-4 r: rsrr\n" +
            "16-18 d: dddddddddddddddtdxdd\n" +
            "4-7 b: bfbbbbsbj\n" +
            "14-15 b: bbgbbbbbbfbbmbbbmb\n" +
            "2-7 b: pbrsbbb\n" +
            "15-16 q: qqqsqqqqqqqbnqqqqq\n" +
            "6-14 k: rbvkkvqrxfklck\n" +
            "2-6 c: klccdm\n" +
            "2-3 b: bpbbs\n" +
            "4-13 p: cppjppppppppmvpppp\n" +
            "1-2 k: kqkpq\n" +
            "8-9 r: rrrrrhrkr\n" +
            "7-9 t: tptftttgwtmt\n" +
            "8-12 g: gfhkgqggznqghqg\n" +
            "15-18 n: pnnnnnnnnnnnnnnnnnn\n" +
            "4-5 p: qpqpq\n" +
            "1-9 h: xhqhhhnthzmhhhrh\n" +
            "4-6 x: bzkxxxhxxwdzpkks\n" +
            "4-5 c: ccccc\n" +
            "9-10 v: vvvvvvvvvv\n" +
            "8-12 d: cdcxdzgddtcfdrxt\n" +
            "7-10 b: bbbsbpbbgbbnj\n" +
            "4-7 z: zznzzzq\n" +
            "1-5 z: zjbzzjdppsbvgbg\n" +
            "2-4 w: lwwwtvjwdjwsbps\n" +
            "1-2 z: bzbvbz\n" +
            "6-14 n: dnnnnqnnnnnnnn\n" +
            "15-18 r: rfbrrwqshczrnbxrvhzr\n" +
            "9-11 f: ffffffffpfz\n" +
            "1-4 k: rskn\n" +
            "5-6 n: njnnnb\n" +
            "3-5 z: zzzzz\n" +
            "7-8 n: nntnnnnn\n" +
            "8-14 k: kkkkkkfkkkkkkkkk\n" +
            "11-16 r: rrqrprrrrrrrrrsvrr\n" +
            "2-10 c: dncjfccpcccccccc\n" +
            "8-20 q: gztqpsqqvthwpfjlqxrq\n" +
            "6-16 n: nnnnnpnnnnnnnnbnnnnn\n" +
            "4-7 h: ghhhwzhhhhhh\n" +
            "10-12 z: zzqzzzcfxzzzwzz\n" +
            "1-3 k: tlkwlkskklxvnk\n" +
            "12-13 n: nnnqqnnnnnnfpn\n" +
            "1-3 l: lnlb\n" +
            "6-9 b: bvfkbrzbwdmbvbql\n" +
            "11-13 d: ddddtdwtjdkdqz\n" +
            "9-15 j: jjcljjjjqjvnjjfjjj\n" +
            "13-14 l: tpllllllllqlll\n" +
            "18-20 d: dddddddddddzdddddtdb\n" +
            "9-15 x: nxxxmnxxxxxxsxxxjwg\n" +
            "6-7 j: rjwvjzjjx\n" +
            "5-6 j: jjjjjjj\n" +
            "8-13 t: ttfttttttttttt\n" +
            "6-16 f: ffrffxfffffffffmf\n" +
            "3-4 f: mhxk\n" +
            "4-9 w: lnwnwwvtvwjww\n" +
            "9-12 d: dwdddqddpdddd\n" +
            "11-16 q: qqqqqqqjzqqpqqlq\n" +
            "2-14 k: zkskkmkrwrdkskq\n" +
            "5-8 v: vqxmvxvvj\n" +
            "3-5 z: zpbwzhrzzwqxr\n" +
            "3-5 c: cccgc\n" +
            "6-9 v: vvvtbvvvvtj\n" +
            "5-6 f: fjwfgdfgtf\n" +
            "1-2 s: svvsnsk\n" +
            "11-13 f: qfpwfmrcfcwfr\n" +
            "3-6 j: jjjxdd\n" +
            "3-6 n: kntwpnn\n" +
            "8-13 v: qgmgcrxvdvkbs\n" +
            "11-16 q: cqsqpqlzqqdhqcqrbgk\n" +
            "1-8 t: pptttttt\n" +
            "11-13 g: ggggggggggkgqgg\n" +
            "4-5 g: gggsgg\n" +
            "10-11 p: rpppfppppmpppp\n" +
            "6-7 q: qqqqqqq\n" +
            "3-11 f: pgfftfflctfd\n" +
            "3-8 s: lswnfsjjdsh\n" +
            "11-13 k: kkkkkkkkkkmksk\n" +
            "3-5 p: pppjpppg\n" +
            "3-4 z: zznrz\n" +
            "8-9 d: ntgdwtdmh\n" +
            "2-3 g: gggl\n" +
            "19-20 q: qqqqqxqqqqqqqqqqqqwd\n" +
            "4-11 n: ljgdnkgftmsvntnn\n" +
            "16-19 t: tttttttttttttttttttt\n";

}
